
// Generated by Cadence Encounter(R) RTL Compiler RC14.22 - v14.20-s016_1

// Verification Directory ../../fv_charrua/SoC 

module SoC(CLK, RST, HOLDn, TEST_EN, TCLK, PROG, BUSY, MOSI, SCLK,
     MISO, BRSTn, PORT_OUT, PORT_IN, PC_OF, PC_UF);
  input CLK, RST, HOLDn, TEST_EN, TCLK, PROG, MOSI, SCLK, BRSTn;
  input [7:0] PORT_IN;
  output BUSY, MISO, PC_OF, PC_UF;
  output [7:0] PORT_OUT;
  wire CLK, RST, HOLDn, TEST_EN, TCLK, PROG, MOSI, SCLK, BRSTn;
  wire [7:0] PORT_IN;
  wire BUSY, MISO, PC_OF, PC_UF;
  wire [7:0] PORT_OUT;
  wire [8:0] CPU_GM_ADDR;
  wire [15:0] CPU_ACC;
  wire [15:0] gm_Q_tmp;
  wire [7:0] PMEM_AD;
  wire [15:0] PMEM_DI;
  wire [15:0] pm_Q;
  wire [1:0] CPU_ZN;
  wire [10:0] CPU_OPERAND;
  wire [4:0] CPU_OPCODE;
  wire [7:0] CPU_INDR;
  wire [10:0] CPU_PC;
  wire [2:0] CPU_state;
  wire [7:0] boot_addr;
  wire [1:0] CPU_APB_GEN_MEM_state;
  wire [15:0] boot_data;
  wire [31:0] BOOTLOADER_INTERFACE_tmp;
  wire [15:0] BOOTLOADER_wdata;
  wire [15:0] CPU_Data_Path_in_alu;
  wire BOOTLOADER_INTERFACE_pwrite_o_tmp, CPU_APB_GEN_MEM_en_w,
       CPU_Control_Unit_n_370, CPU_Control_Unit_n_415,
       CPU_Control_Unit_n_848, CPU_Data_Path_add_103_26_n_72,
       CPU_Data_Path_add_105_28_n_47, CPU_Data_Path_add_105_28_n_53;
  wire CPU_Data_Path_add_105_28_n_57, CPU_Data_Path_add_105_28_n_59,
       CPU_Data_Path_add_105_28_n_63, CPU_Data_Path_add_105_28_n_76,
       CPU_Data_Path_add_105_28_n_109, CPU_Data_Path_add_105_28_n_9136,
       CPU_Data_Path_add_105_28_n_9139, CPU_Data_Path_add_105_28_n_9140;
  wire CPU_Data_Path_n_7530, CPU_SEL_BRANCH, CPU_en_ACC,
       GMEM_READY_HIGH, GMEM_READY_LOW, PMEM_READY_HIGH,
       PMEM_READY_LOW, PMEM_WR;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, gm_we,
       n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_111, n_112, n_114, n_115, n_116, n_117, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_139, n_140, n_141, n_142, n_143, n_144, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_179;
  wire n_180, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_281, n_282, n_283, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_292, n_293;
  wire n_294, n_295, n_296, n_297, n_298, n_299, n_300, n_301;
  wire n_302, n_303, n_304, n_305, n_306, n_307, n_308, n_309;
  wire n_310, n_311, n_312, n_313, n_314, n_315, n_316, n_317;
  wire n_318, n_319, n_320, n_321, n_322, n_323, n_324, n_325;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341;
  wire n_342, n_343, n_344, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, n_362, n_363, n_364, n_365, n_366;
  wire n_367, n_368, n_369, n_370, n_371, n_372, n_374, n_375;
  wire n_376, n_377, n_378, n_379, n_380, n_381, n_382, n_383;
  wire n_384, n_386, n_387, n_388, n_389, n_390, n_391, n_392;
  wire n_393, n_394, n_395, n_396, n_397, n_398, n_399, n_400;
  wire n_401, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_419, n_420, n_421, n_422, n_423, n_424, n_425;
  wire n_426, n_427, n_429, n_430, n_431, n_432, n_433, n_434;
  wire n_435, n_436, n_437, n_438, n_439, n_440, n_441, n_442;
  wire n_443, n_444, n_446, n_447, n_448, n_449, n_450, n_451;
  wire n_452, n_453, n_454, n_455, n_456, n_457, n_458, n_459;
  wire n_460, n_461, n_462, n_463, n_464, n_465, n_466, n_467;
  wire n_468, n_469, n_470, n_471, n_472, n_473, n_474, n_475;
  wire n_477, n_478, n_479, n_480, n_481, n_482, n_483, n_484;
  wire n_485, n_486, n_487, n_488, n_489, n_490, n_491, n_492;
  wire n_493, n_494, n_495, n_496, n_497, n_498, n_499, n_500;
  wire n_501, n_502, n_503, n_504, n_505, n_506, n_507, n_508;
  wire n_509, n_511, n_512, n_513, n_514, n_515, n_516, n_517;
  wire n_518, n_519, n_520, n_521, n_522, n_523, n_524, n_525;
  wire n_526, n_527, n_528, n_529, n_530, n_531, n_532, n_533;
  wire n_534, n_535, n_536, n_537, n_538, n_539, n_540, n_541;
  wire n_542, n_543, n_544, n_545, n_546, n_547, n_548, n_549;
  wire n_550, n_551, n_552, n_553, n_554, n_555, n_556, n_557;
  wire n_558, n_559, n_560, n_561, n_562, n_563, n_564, n_565;
  wire n_566, n_567, n_568, n_569, n_570, n_571, n_572, n_573;
  wire n_574, n_575, n_576, n_577, n_578, n_579, n_580, n_581;
  wire n_582, n_583, n_584, n_585, n_586, n_587, n_588, n_589;
  wire n_590, n_591, n_592, n_593, n_594, n_595, n_596, n_597;
  wire n_598, n_599, n_600, n_601, n_602, n_603, n_604, n_605;
  wire n_606, n_607, n_608, n_609, n_610, n_611, n_612, n_613;
  wire n_614, n_615, n_616, n_617, n_618, n_619, n_620, n_621;
  wire n_622, n_623, n_624, n_625, n_626, n_627, n_628, n_629;
  wire n_630, n_631, n_632, n_633, n_634, n_635, n_636, n_637;
  wire n_638, n_639, n_640, n_641, n_642, n_643, n_644, n_645;
  wire n_646, n_647, n_648, n_649, n_650, n_651, n_652, n_653;
  wire n_655, n_656, n_657, n_658, n_659, n_660, n_661, n_662;
  wire n_664, n_665, n_666, n_667, n_668, n_669, n_670, n_671;
  wire n_673, n_674, n_675, n_676, n_677, n_678, n_679, n_680;
  wire n_681, n_682, n_684, n_685, n_686, n_687, n_688, n_690;
  wire n_691, n_692, n_693, n_694, n_695, n_697, n_698, n_699;
  wire n_700, n_701, n_702, n_703, n_704, n_705, n_706, n_707;
  wire n_708, n_709, n_710, n_711, n_712, n_713, n_714, n_715;
  wire n_716, n_717, n_718, n_719, n_720, n_721, n_722, n_723;
  wire n_724, n_725, n_726, n_727, n_728, n_729, n_730, n_731;
  wire n_732, n_733, n_734, n_735, n_736, n_737, n_738, n_739;
  wire n_740, n_741, n_742, n_743, n_744, n_745, n_746, n_747;
  wire n_748, n_749, n_750, n_751, n_752, n_753, n_754, n_755;
  wire n_756, n_757, n_758, n_759, n_760, n_761, n_762, n_763;
  wire n_764, n_765, n_766, n_767, n_768, n_769, n_770, n_771;
  wire n_772, n_773, n_774, n_775, n_776, n_777, n_778, n_779;
  wire n_780, n_781, n_782, n_783, n_784, n_785, n_786, n_787;
  wire n_788, n_789, n_790, n_791, n_792, n_793, n_794, n_795;
  wire n_796, n_797, n_798, n_799, n_800, n_801, n_802, n_803;
  wire n_804, n_805, n_806, n_807, n_808, n_809, n_810, n_811;
  wire n_812, n_813, n_814, n_815, n_816, n_817, n_818, n_819;
  wire n_820, n_821, n_822, n_823, n_824, n_825, n_826, n_827;
  wire n_828, n_829, n_830, n_831, n_832, n_833, n_834, n_835;
  wire n_836, n_837, n_838, n_839, n_840, n_841, n_842, n_843;
  wire n_845, n_846, n_847, n_850, n_851, n_852, n_854, n_855;
  wire n_871, n_872, n_873, n_874, n_875, n_876, n_877, n_878;
  wire n_879, n_880, n_881, n_882, n_883, n_884, n_885, n_886;
  wire n_887, n_889, n_890, n_891, n_892, n_895, n_896, n_897;
  wire n_898, n_899, n_901, n_902, n_905, n_906, n_909, n_911;
  wire n_913, n_914, n_915, n_916, n_922, n_923, n_925, n_928;
  wire n_941, n_951, n_960, n_961, n_962, n_963, n_964, n_966;
  wire n_967, n_974, n_990, n_1003, n_1016, n_1029, n_1042, n_1055;
  wire n_1073, n_1086, n_1099, n_1112, n_1125, n_1138, n_1151, n_1164;
  wire n_1167, n_1168, n_1169, n_1170, n_1171, n_1172, n_1173, n_1174;
  wire n_1175, n_1176, n_1177, n_1178, n_1179, n_1180, n_1181;
  SPRAM256X8 GMEM_HIGH(.CS (n_925), .AD (CPU_GM_ADDR[7:0]), .RD
       (gm_we), .EN (1'b0), .WR (n_923), .NRST (RST), .DI
       ({CPU_ACC[15], n_1086, n_1125, CPU_ACC[12:11], n_1138, n_1151,
       CPU_ACC[8]}), .READY (GMEM_READY_HIGH), .DO (gm_Q_tmp[15:8]),
       .ramgnd (1'b0), .ramvdd (1'b1));
  SPRAM256X8 GMEM_LOW(.CS (n_925), .AD (CPU_GM_ADDR[7:0]), .RD (gm_we),
       .EN (1'b0), .WR (n_923), .NRST (RST), .DI ({CPU_ACC[7:4],
       n_1112, CPU_ACC[2], n_1164, n_1099}), .READY (GMEM_READY_LOW),
       .DO (gm_Q_tmp[7:0]), .ramgnd (1'b0), .ramvdd (1'b1));
  SPRAM256X8 PMEM_HIGH(.CS (CLK), .AD (PMEM_AD), .RD (n_922), .EN
       (1'b0), .WR (PMEM_WR), .NRST (RST), .DI (PMEM_DI[15:8]), .READY
       (PMEM_READY_HIGH), .DO (pm_Q[15:8]), .ramgnd (1'b0), .ramvdd
       (1'b1));
  SPRAM256X8 PMEM_LOW(.CS (CLK), .AD (PMEM_AD), .RD (n_922), .EN
       (1'b0), .WR (PMEM_WR), .NRST (RST), .DI (PMEM_DI[7:0]), .READY
       (PMEM_READY_LOW), .DO (pm_Q[7:0]), .ramgnd (1'b0), .ramvdd
       (1'b1));
  INST_X4 g9848(.A (gm_we), .Q (n_923));
  INST_X4 g9849(.A (PMEM_WR), .Q (n_922));
  DFRRQST_X2 \CPU_Data_Path_ZN_reg[0] (.RN (RST), .C (CLK), .D
       (CPU_ACC[15]), .Q (CPU_ZN[0]));
  DFRRQST_X2 \CPU_Data_Path_ZN_reg[1] (.RN (RST), .C (CLK), .D (n_909),
       .Q (CPU_ZN[1]));
  ON31ST_X1 g18796(.A (CPU_SEL_BRANCH), .B (n_911), .C
       (CPU_OPERAND[8]), .D (n_1177), .Q (PC_OF));
  AND2ST_X2 g18797(.A (n_911), .B (n_850), .Q (PC_UF));
  ON31ST_X1 g18800(.A (n_915), .B (CPU_Control_Unit_n_415), .C
       (n_1179), .D (n_960), .Q (n_916));
  NA2ST_X1 g18801(.A (n_902), .B (n_913), .Q (n_915));
  NO2ST_X1 g18802(.A (n_1167), .B (n_1175), .Q (n_914));
  NA4I2ST_X1 g18804(.AN (CPU_ZN[0]), .BN (CPU_ZN[1]), .C
       (CPU_OPCODE[1]), .D (n_852), .Q (n_913));
  AO21ST_X2 g18810(.A (CPU_Data_Path_add_105_28_n_109), .B (n_906), .C
       (CPU_Data_Path_add_105_28_n_59), .Q (n_911));
  OR2ST_X1 g18816(.A (n_843), .B (CPU_GM_ADDR[8]), .Q (gm_we));
  MU2ST_X1 g18817(.IN0 (CPU_OPERAND[2]), .IN1 (CPU_INDR[2]), .S
       (n_905), .Q (CPU_GM_ADDR[2]));
  MU2ST_X1 g18818(.IN0 (CPU_OPERAND[1]), .IN1 (CPU_INDR[1]), .S
       (n_905), .Q (CPU_GM_ADDR[1]));
  MU2ST_X1 g18819(.IN0 (CPU_OPERAND[0]), .IN1 (CPU_INDR[0]), .S
       (n_905), .Q (CPU_GM_ADDR[0]));
  MU2ST_X1 g18820(.IN0 (CPU_OPERAND[7]), .IN1 (CPU_INDR[7]), .S
       (n_905), .Q (CPU_GM_ADDR[7]));
  MU2ST_X1 g18821(.IN0 (CPU_OPERAND[6]), .IN1 (CPU_INDR[6]), .S
       (n_905), .Q (CPU_GM_ADDR[6]));
  MU2ST_X1 g18822(.IN0 (CPU_OPERAND[5]), .IN1 (CPU_INDR[5]), .S
       (n_905), .Q (CPU_GM_ADDR[5]));
  MU2ST_X1 g18823(.IN0 (CPU_OPERAND[4]), .IN1 (CPU_INDR[4]), .S
       (n_905), .Q (CPU_GM_ADDR[4]));
  MU2ST_X1 g18824(.IN0 (CPU_OPERAND[3]), .IN1 (CPU_INDR[3]), .S
       (n_905), .Q (CPU_GM_ADDR[3]));
  NO5I4ST_X1 g18825(.AN (n_885), .BN (n_886), .CN (n_887), .DN (n_889),
       .E (CPU_ACC[15]), .Q (n_909));
  OA21ST_X2 g18827(.A (n_899), .B (n_896), .C (CPU_OPERAND[8]), .Q
       (CPU_GM_ADDR[8]));
  AN21ST_X1 g18829(.A (n_901), .B (n_855), .C (n_890), .Q (n_906));
  AND2ST_X1 g18830(.A (CPU_Data_Path_add_105_28_n_76), .B (n_880), .Q
       (n_941));
  AND4ST_X1 g18831(.A (n_1016), .B (n_892), .C (n_891), .D (n_928), .Q
       (n_905));
  NA4I2ST_X1 g18834(.AN (n_96), .BN (CPU_ZN[0]), .C (CPU_OPCODE[0]), .D
       (n_845), .Q (n_902));
  INST_X3 g18835(.A (n_901), .Q (CPU_Data_Path_add_105_28_n_9140));
  OA21ST_X1 g18836(.A (n_876), .B (n_877), .C (n_883), .Q (n_901));
  INST_X4 g18840(.A (n_899), .Q (CPU_Data_Path_n_7530));
  NA4I2ST_X1 g18841(.AN (n_990), .BN (CPU_OPCODE[1]), .C (n_1016), .D
       (n_1029), .Q (n_899));
  INST_X3 g18842(.A (n_898), .Q (CPU_Data_Path_add_103_26_n_72));
  AND2ST_X2 g18843(.A (n_895), .B (CPU_PC[3]), .Q (n_898));
  AND3ST_X4 g18846(.A (n_883), .B (n_855), .C (n_882), .Q (n_897));
  AO21ST_X1 g18847(.A (n_879), .B (n_875), .C (n_951), .Q
       (CPU_Data_Path_add_105_28_n_76));
  MU2ST_X2 g18848(.IN0 (n_878), .IN1 (n_881), .S (CPU_state[2]), .Q
       (n_896));
  INST_X3 g18849(.A (n_66), .Q (n_65));
  AND2ST_X2 g18853(.A (n_872), .B (CPU_PC[2]), .Q (n_895));
  NO2I1ST_X1 g18854(.AN (n_1073), .B (n_881), .Q (CPU_en_ACC));
  NA2I1ST_X1 g18855(.AN (n_1073), .B (n_878), .Q (n_892));
  NA2ST_X1 g18856(.A (n_881), .B (CPU_state[2]), .Q (n_891));
  AND3ST_X4 g18858(.A (n_1029), .B (n_96), .C (n_847), .Q (n_928));
  NA2ST_X1 g18860(.A (n_873), .B (n_871), .Q (n_890));
  NO3ST_X1 g18861(.A (CPU_ACC[1]), .B (CPU_ACC[2]), .C (n_1055), .Q
       (n_889));
  NO4ST_X1 g18863(.A (CPU_ACC[3]), .B (CPU_ACC[9]), .C (CPU_ACC[8]), .D
       (CPU_ACC[11]), .Q (n_887));
  NO4ST_X1 g18865(.A (CPU_ACC[4]), .B (CPU_ACC[7]), .C (n_1042), .D
       (CPU_ACC[14]), .Q (n_886));
  NO4ST_X1 g18866(.A (CPU_ACC[0]), .B (CPU_ACC[12]), .C (CPU_ACC[10]),
       .D (CPU_ACC[13]), .Q (n_885));
  AND4ST_X1 g18867(.A (n_96), .B (CPU_OPCODE[3]), .C (CPU_OPCODE[2]),
       .D (n_846), .Q (CPU_Control_Unit_n_370));
  MU2ST_X2 g18868(.IN0 (CPU_PC[7]), .IN1 (boot_addr[7]), .S (PROG), .Q
       (PMEM_AD[7]));
  MU2ST_X2 g18869(.IN0 (CPU_PC[6]), .IN1 (boot_addr[6]), .S (PROG), .Q
       (PMEM_AD[6]));
  MU2ST_X2 g18870(.IN0 (CPU_PC[5]), .IN1 (boot_addr[5]), .S (PROG), .Q
       (PMEM_AD[5]));
  MU2ST_X2 g18871(.IN0 (CPU_PC[4]), .IN1 (boot_addr[4]), .S (PROG), .Q
       (PMEM_AD[4]));
  MU2ST_X2 g18872(.IN0 (CPU_PC[3]), .IN1 (boot_addr[3]), .S (PROG), .Q
       (PMEM_AD[3]));
  MU2ST_X2 g18873(.IN0 (CPU_PC[2]), .IN1 (boot_addr[2]), .S (PROG), .Q
       (PMEM_AD[2]));
  MU2ST_X2 g18874(.IN0 (CPU_PC[1]), .IN1 (boot_addr[1]), .S (PROG), .Q
       (PMEM_AD[1]));
  MU2ST_X2 g18875(.IN0 (CPU_PC[0]), .IN1 (boot_addr[0]), .S (PROG), .Q
       (PMEM_AD[0]));
  EN2ST_X1 g18876(.A (CPU_APB_GEN_MEM_state[1]), .B
       (CPU_APB_GEN_MEM_state[0]), .Q (n_884));
  INST_X3 g18877(.A (n_855), .Q (CPU_Data_Path_add_105_28_n_63));
  INST_X3 g18879(.A (n_883), .Q (CPU_Data_Path_add_105_28_n_53));
  INST_X3 g18880(.A (n_882), .Q (CPU_Data_Path_add_105_28_n_57));
  INST_X2 g18881(.A (n_854), .Q (CPU_Data_Path_add_105_28_n_47));
  OR2ST_X1 g18886(.A (CPU_OPERAND[6]), .B (CPU_PC[6]), .Q (n_855));
  OR2ST_X1 g18887(.A (CPU_OPERAND[5]), .B (CPU_PC[5]), .Q (n_883));
  OR2ST_X1 g18889(.A (CPU_OPERAND[4]), .B (CPU_PC[4]), .Q (n_882));
  OR2ST_X1 g18890(.A (CPU_OPERAND[3]), .B (CPU_PC[3]), .Q (n_854));
  OR2ST_X1 g18891(.A (CPU_state[1]), .B (CPU_state[0]), .Q (n_881));
  NO2ST_X1 g18892(.A (CPU_OPERAND[7]), .B (CPU_PC[7]), .Q
       (CPU_Data_Path_add_105_28_n_59));
  OR2ST_X1 g18893(.A (CPU_OPERAND[2]), .B (CPU_PC[2]), .Q (n_880));
  OR2ST_X1 g18894(.A (CPU_OPERAND[1]), .B (CPU_PC[1]), .Q (n_879));
  NA2ST_X1 g18895(.A (CPU_state[0]), .B (CPU_state[1]), .Q (n_878));
  AND2ST_X2 g18896(.A (boot_data[15]), .B (PROG), .Q (PMEM_DI[15]));
  AND2ST_X2 g18897(.A (boot_data[14]), .B (PROG), .Q (PMEM_DI[14]));
  AND2ST_X2 g18898(.A (boot_data[13]), .B (PROG), .Q (PMEM_DI[13]));
  AND2ST_X2 g18899(.A (boot_data[12]), .B (PROG), .Q (PMEM_DI[12]));
  AND2ST_X2 g18900(.A (boot_data[11]), .B (PROG), .Q (PMEM_DI[11]));
  AND2ST_X2 g18901(.A (boot_data[10]), .B (PROG), .Q (PMEM_DI[10]));
  AND2ST_X2 g18902(.A (boot_data[9]), .B (PROG), .Q (PMEM_DI[9]));
  AND2ST_X2 g18903(.A (CPU_PC[5]), .B (CPU_OPERAND[5]), .Q (n_877));
  INST_X3 g18904(.A (n_876), .Q (CPU_Data_Path_add_105_28_n_9139));
  INST_X3 g18906(.A (n_874), .Q (CPU_Data_Path_add_105_28_n_9136));
  AND2ST_X2 g18909(.A (CPU_PC[4]), .B (CPU_OPERAND[4]), .Q (n_876));
  AND2ST_X2 g18910(.A (boot_data[7]), .B (PROG), .Q (PMEM_DI[7]));
  AND2ST_X2 g18911(.A (boot_data[6]), .B (PROG), .Q (PMEM_DI[6]));
  AND2ST_X2 g18912(.A (boot_data[5]), .B (PROG), .Q (PMEM_DI[5]));
  AND2ST_X2 g18913(.A (boot_data[4]), .B (PROG), .Q (PMEM_DI[4]));
  AND2ST_X2 g18914(.A (boot_data[3]), .B (PROG), .Q (PMEM_DI[3]));
  AND2ST_X2 g18915(.A (CPU_PC[0]), .B (CPU_OPERAND[0]), .Q (n_875));
  AND2ST_X2 g18916(.A (boot_data[2]), .B (PROG), .Q (PMEM_DI[2]));
  AND2ST_X2 g18917(.A (boot_data[1]), .B (PROG), .Q (PMEM_DI[1]));
  AND2ST_X2 g18918(.A (n_974), .B (n_96), .Q (CPU_Control_Unit_n_848));
  NO2I1ST_X1 g18919(.AN (PROG), .B (BOOTLOADER_INTERFACE_pwrite_o_tmp),
       .Q (PMEM_WR));
  AND2ST_X2 g18920(.A (boot_data[8]), .B (PROG), .Q (PMEM_DI[8]));
  NA2ST_X1 g18921(.A (CPU_PC[7]), .B (CPU_OPERAND[7]), .Q (n_871));
  AND2ST_X2 g18922(.A (boot_data[0]), .B (PROG), .Q (PMEM_DI[0]));
  AND2ST_X2 g18923(.A (CPU_PC[2]), .B (CPU_OPERAND[2]), .Q (n_874));
  NA2ST_X1 g18924(.A (CPU_PC[6]), .B (CPU_OPERAND[6]), .Q (n_873));
  AND2ST_X2 g18925(.A (CPU_PC[1]), .B (CPU_OPERAND[1]), .Q (n_951));
  AND2ST_X2 g18926(.A (CPU_PC[0]), .B (CPU_PC[1]), .Q (n_872));
  INST_X3 g18940(.A (CLK), .Q (n_925));
  AND3ST_X4 g18857_dup(.A (CPU_OPCODE[3]), .B (n_846), .C (n_847), .Q
       (n_852));
  AN21ST_X1 g2(.A (n_916), .B (n_914), .C (n_851), .Q (n_850));
  NA3I2ST_X2 g3(.AN (CPU_state[2]), .BN (n_878), .C (CPU_OPERAND[8]),
       .Q (n_851));
  AO21ST_X1 g18954(.A (n_916), .B (n_914), .C (n_66), .Q
       (CPU_SEL_BRANCH));
  OR2ST_X1 g18955(.A (CPU_state[2]), .B (n_878), .Q (n_66));
  AND3ST_X2 g18958(.A (n_1016), .B (n_847), .C (n_846), .Q (n_845));
  NO3I2ST_X2 g18970(.AN (n_852), .BN (CPU_Control_Unit_n_848), .C
       (CPU_ZN[1]), .Q (CPU_Control_Unit_n_415));
  ON211ST_X1 g18995(.A (n_941), .B (n_1178), .C (n_897), .D (n_854), .Q
       (CPU_Data_Path_add_105_28_n_109));
  NA2I1ST_X1 g18996(.AN (n_884), .B (CPU_APB_GEN_MEM_en_w), .Q (n_843));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[0] (.RN (BRSTn), .C
       (CLK), .D (n_825), .Q (boot_addr[0]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[1] (.RN (BRSTn), .C
       (CLK), .D (n_824), .Q (boot_addr[1]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[2] (.RN (BRSTn), .C
       (CLK), .D (n_822), .Q (boot_addr[2]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[3] (.RN (BRSTn), .C
       (CLK), .D (n_823), .Q (boot_addr[3]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[4] (.RN (BRSTn), .C
       (CLK), .D (n_821), .Q (boot_addr[4]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[5] (.RN (BRSTn), .C
       (CLK), .D (n_820), .Q (boot_addr[5]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[6] (.RN (BRSTn), .C
       (CLK), .D (n_819), .Q (boot_addr[6]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_address_o_reg[7] (.RN (BRSTn), .C
       (CLK), .D (n_818), .Q (boot_addr[7]));
  DFRSQST_X2 BOOTLOADER_INTERFACE_pwrite_o_tmp_reg(.SN (BRSTn), .C
       (CLK), .D (n_817), .Q (BOOTLOADER_INTERFACE_pwrite_o_tmp));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[0] (.RN (BRSTn), .C (CLK),
       .D (n_180), .Q (BOOTLOADER_INTERFACE_tmp[0]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[10] (.RN (BRSTn), .C (CLK),
       .D (n_729), .Q (BOOTLOADER_INTERFACE_tmp[10]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[11] (.RN (BRSTn), .C (CLK),
       .D (n_738), .Q (BOOTLOADER_INTERFACE_tmp[11]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[12] (.RN (BRSTn), .C (CLK),
       .D (n_747), .Q (BOOTLOADER_INTERFACE_tmp[12]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[13] (.RN (BRSTn), .C (CLK),
       .D (n_752), .Q (BOOTLOADER_INTERFACE_tmp[13]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[14] (.RN (BRSTn), .C (CLK),
       .D (n_755), .Q (BOOTLOADER_INTERFACE_tmp[14]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[15] (.RN (BRSTn), .C (CLK),
       .D (n_758), .Q (BOOTLOADER_INTERFACE_tmp[15]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[16] (.RN (BRSTn), .C (CLK),
       .D (n_761), .Q (BOOTLOADER_INTERFACE_tmp[16]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[17] (.RN (BRSTn), .C (CLK),
       .D (n_764), .Q (BOOTLOADER_INTERFACE_tmp[17]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[18] (.RN (BRSTn), .C (CLK),
       .D (n_767), .Q (BOOTLOADER_INTERFACE_tmp[18]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[19] (.RN (BRSTn), .C (CLK),
       .D (n_770), .Q (BOOTLOADER_INTERFACE_tmp[19]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[1] (.RN (BRSTn), .C (CLK),
       .D (n_349), .Q (BOOTLOADER_INTERFACE_tmp[1]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[20] (.RN (BRSTn), .C (CLK),
       .D (n_773), .Q (BOOTLOADER_INTERFACE_tmp[20]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[21] (.RN (BRSTn), .C (CLK),
       .D (n_776), .Q (BOOTLOADER_INTERFACE_tmp[21]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[22] (.RN (BRSTn), .C (CLK),
       .D (n_779), .Q (BOOTLOADER_INTERFACE_tmp[22]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[23] (.RN (BRSTn), .C (CLK),
       .D (n_782), .Q (BOOTLOADER_INTERFACE_tmp[23]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[24] (.RN (BRSTn), .C (CLK),
       .D (n_785), .Q (BOOTLOADER_INTERFACE_tmp[24]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[25] (.RN (BRSTn), .C (CLK),
       .D (n_788), .Q (BOOTLOADER_INTERFACE_tmp[25]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[26] (.RN (BRSTn), .C (CLK),
       .D (n_792), .Q (BOOTLOADER_INTERFACE_tmp[26]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[27] (.RN (BRSTn), .C (CLK),
       .D (n_795), .Q (BOOTLOADER_INTERFACE_tmp[27]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[28] (.RN (BRSTn), .C (CLK),
       .D (n_798), .Q (BOOTLOADER_INTERFACE_tmp[28]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[29] (.RN (BRSTn), .C (CLK),
       .D (n_801), .Q (BOOTLOADER_INTERFACE_tmp[29]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[2] (.RN (BRSTn), .C (CLK),
       .D (n_420), .Q (BOOTLOADER_INTERFACE_tmp[2]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[30] (.RN (BRSTn), .C (CLK),
       .D (n_805), .Q (BOOTLOADER_INTERFACE_tmp[30]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[31] (.RN (BRSTn), .C (CLK),
       .D (n_807), .Q (BOOTLOADER_INTERFACE_tmp[31]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[3] (.RN (BRSTn), .C (CLK),
       .D (n_479), .Q (BOOTLOADER_INTERFACE_tmp[3]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[4] (.RN (BRSTn), .C (CLK),
       .D (n_523), .Q (BOOTLOADER_INTERFACE_tmp[4]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_tmp_reg[5] (.RN (BRSTn), .C (CLK),
       .D (n_842), .Q (BOOTLOADER_INTERFACE_tmp[5]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[6] (.RN (BRSTn), .C (CLK),
       .D (n_646), .Q (BOOTLOADER_INTERFACE_tmp[6]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[7] (.RN (BRSTn), .C (CLK),
       .D (n_676), .Q (BOOTLOADER_INTERFACE_tmp[7]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[8] (.RN (BRSTn), .C (CLK),
       .D (n_698), .Q (BOOTLOADER_INTERFACE_tmp[8]));
  DFRRQST_X2 \BOOTLOADER_INTERFACE_tmp_reg[9] (.RN (BRSTn), .C (CLK),
       .D (n_715), .Q (BOOTLOADER_INTERFACE_tmp[9]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[0] (.RN (BRSTn), .C
       (CLK), .D (n_841), .Q (boot_data[0]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[10] (.RN (BRSTn), .C
       (CLK), .D (n_840), .Q (boot_data[10]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[11] (.RN (BRSTn), .C
       (CLK), .D (n_839), .Q (boot_data[11]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[12] (.RN (BRSTn), .C
       (CLK), .D (n_838), .Q (boot_data[12]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[13] (.RN (BRSTn), .C
       (CLK), .D (n_837), .Q (boot_data[13]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[14] (.RN (BRSTn), .C
       (CLK), .D (n_836), .Q (boot_data[14]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[15] (.RN (BRSTn), .C
       (CLK), .D (n_835), .Q (boot_data[15]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[1] (.RN (BRSTn), .C
       (CLK), .D (n_832), .Q (boot_data[1]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[2] (.RN (BRSTn), .C
       (CLK), .D (n_834), .Q (boot_data[2]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[3] (.RN (BRSTn), .C
       (CLK), .D (n_833), .Q (boot_data[3]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[4] (.RN (BRSTn), .C
       (CLK), .D (n_831), .Q (boot_data[4]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[5] (.RN (BRSTn), .C
       (CLK), .D (n_830), .Q (boot_data[5]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[6] (.RN (BRSTn), .C
       (CLK), .D (n_829), .Q (boot_data[6]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[7] (.RN (BRSTn), .C
       (CLK), .D (n_828), .Q (boot_data[7]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[8] (.RN (BRSTn), .C
       (CLK), .D (n_827), .Q (boot_data[8]));
  DFRRQST_X1 \BOOTLOADER_INTERFACE_wdata_o_reg[9] (.RN (BRSTn), .C
       (CLK), .D (n_826), .Q (boot_data[9]));
  DFRRQST_X2 BOOTLOADER_SPI_miso_reg(.RN (BRSTn), .C (CLK), .D (n_199),
       .Q (MISO));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[0] (.RN (BRSTn), .C (CLK),
       .D (n_186), .Q (BOOTLOADER_wdata[0]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[10] (.RN (BRSTn), .C (CLK),
       .D (n_198), .Q (BOOTLOADER_wdata[10]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[11] (.RN (BRSTn), .C (CLK),
       .D (n_197), .Q (BOOTLOADER_wdata[11]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[12] (.RN (BRSTn), .C (CLK),
       .D (n_195), .Q (BOOTLOADER_wdata[12]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[13] (.RN (BRSTn), .C (CLK),
       .D (n_184), .Q (BOOTLOADER_wdata[13]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[14] (.RN (BRSTn), .C (CLK),
       .D (n_185), .Q (BOOTLOADER_wdata[14]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[15] (.RN (BRSTn), .C (CLK),
       .D (n_194), .Q (BOOTLOADER_wdata[15]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[1] (.RN (BRSTn), .C (CLK),
       .D (n_192), .Q (BOOTLOADER_wdata[1]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[2] (.RN (BRSTn), .C (CLK),
       .D (n_196), .Q (BOOTLOADER_wdata[2]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[3] (.RN (BRSTn), .C (CLK),
       .D (n_191), .Q (BOOTLOADER_wdata[3]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[4] (.RN (BRSTn), .C (CLK),
       .D (n_189), .Q (BOOTLOADER_wdata[4]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[5] (.RN (BRSTn), .C (CLK),
       .D (n_183), .Q (BOOTLOADER_wdata[5]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[6] (.RN (BRSTn), .C (CLK),
       .D (n_193), .Q (BOOTLOADER_wdata[6]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[7] (.RN (BRSTn), .C (CLK),
       .D (n_190), .Q (BOOTLOADER_wdata[7]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[8] (.RN (BRSTn), .C (CLK),
       .D (n_188), .Q (BOOTLOADER_wdata[8]));
  DFRRQST_X2 \BOOTLOADER_SPI_wdata_tmp_reg[9] (.RN (BRSTn), .C (CLK),
       .D (n_187), .Q (BOOTLOADER_wdata[9]));
  DFRSQST_X2 CPU_APB_GEN_MEM_en_w_reg(.SN (1'b1), .C (CLK), .D (n_425),
       .Q (CPU_APB_GEN_MEM_en_w));
  DFRRQST_X2 \CPU_APB_GEN_MEM_state_reg[0] (.RN (RST), .C (CLK), .D
       (n_966), .Q (CPU_APB_GEN_MEM_state[0]));
  DFRRQST_X2 \CPU_APB_GEN_MEM_state_reg[1] (.RN (RST), .C (CLK), .D
       (n_266), .Q (CPU_APB_GEN_MEM_state[1]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[0] (.RN (RST), .C (CLK), .D
       (n_304), .Q (CPU_OPERAND[0]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[10] (.RN (RST), .C (CLK), .D
       (n_305), .Q (CPU_OPERAND[10]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[11] (.RN (RST), .C (CLK), .D
       (n_307), .Q (CPU_OPCODE[0]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[12] (.RN (RST), .C (CLK), .D
       (n_317), .Q (CPU_OPCODE[1]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[13] (.RN (RST), .C (CLK), .D
       (n_316), .Q (CPU_OPCODE[2]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[14] (.RN (RST), .C (CLK), .D
       (n_315), .Q (CPU_OPCODE[3]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[15] (.RN (RST), .C (CLK), .D
       (n_314), .Q (CPU_OPCODE[4]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[1] (.RN (RST), .C (CLK), .D
       (n_318), .Q (CPU_OPERAND[1]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[2] (.RN (RST), .C (CLK), .D
       (n_312), .Q (CPU_OPERAND[2]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[3] (.RN (RST), .C (CLK), .D
       (n_319), .Q (CPU_OPERAND[3]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[4] (.RN (RST), .C (CLK), .D
       (n_309), .Q (CPU_OPERAND[4]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[5] (.RN (RST), .C (CLK), .D
       (n_313), .Q (CPU_OPERAND[5]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[6] (.RN (RST), .C (CLK), .D
       (n_311), .Q (CPU_OPERAND[6]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[7] (.RN (RST), .C (CLK), .D
       (n_310), .Q (CPU_OPERAND[7]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[8] (.RN (RST), .C (CLK), .D
       (n_306), .Q (CPU_OPERAND[8]));
  DFRRQST_X2 \CPU_Control_Unit_INST_reg[9] (.RN (RST), .C (CLK), .D
       (n_308), .Q (CPU_OPERAND[9]));
  DFRRQST_X2 \CPU_Control_Unit_state_reg[0] (.RN (RST), .C (CLK), .D
       (n_384), .Q (CPU_state[0]));
  DFRRQST_X2 \CPU_Control_Unit_state_reg[1] (.RN (RST), .C (CLK), .D
       (n_383), .Q (CPU_state[1]));
  DFRRQST_X2 \CPU_Control_Unit_state_reg[2] (.RN (RST), .C (CLK), .D
       (n_401), .Q (CPU_state[2]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[0] (.RN (RST), .C (CLK), .D
       (n_673), .Q (CPU_ACC[0]));
  DFRRQST_X1 \CPU_Data_Path_ACC_reg[10] (.RN (RST), .C (CLK), .D
       (n_719), .Q (CPU_ACC[10]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[11] (.RN (RST), .C (CLK), .D
       (n_728), .Q (CPU_ACC[11]));
  DFRRQST_X1 \CPU_Data_Path_ACC_reg[12] (.RN (RST), .C (CLK), .D
       (n_733), .Q (CPU_ACC[12]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[13] (.RN (RST), .C (CLK), .D
       (n_744), .Q (CPU_ACC[13]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[14] (.RN (RST), .C (CLK), .D
       (n_746), .Q (CPU_ACC[14]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[15] (.RN (RST), .C (CLK), .D
       (n_751), .Q (CPU_ACC[15]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[1] (.RN (RST), .C (CLK), .D
       (n_690), .Q (CPU_ACC[1]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[2] (.RN (RST), .C (CLK), .D
       (n_680), .Q (CPU_ACC[2]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[3] (.RN (RST), .C (CLK), .D
       (n_681), .Q (CPU_ACC[3]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[4] (.RN (RST), .C (CLK), .D
       (n_661), .Q (CPU_ACC[4]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[5] (.RN (RST), .C (CLK), .D
       (n_655), .Q (CPU_ACC[5]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[6] (.RN (RST), .C (CLK), .D
       (n_664), .Q (CPU_ACC[6]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[7] (.RN (RST), .C (CLK), .D
       (n_688), .Q (CPU_ACC[7]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[8] (.RN (RST), .C (CLK), .D
       (n_697), .Q (CPU_ACC[8]));
  DFRRQST_X2 \CPU_Data_Path_ACC_reg[9] (.RN (RST), .C (CLK), .D
       (n_708), .Q (CPU_ACC[9]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[0] (.RN (RST), .C (CLK), .D
       (n_436), .Q (CPU_INDR[0]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[1] (.RN (RST), .C (CLK), .D
       (n_456), .Q (CPU_INDR[1]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[2] (.RN (RST), .C (CLK), .D
       (n_524), .Q (CPU_INDR[2]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[3] (.RN (RST), .C (CLK), .D
       (n_601), .Q (CPU_INDR[3]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[4] (.RN (RST), .C (CLK), .D
       (n_647), .Q (CPU_INDR[4]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[5] (.RN (RST), .C (CLK), .D
       (n_677), .Q (CPU_INDR[5]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[6] (.RN (RST), .C (CLK), .D
       (n_699), .Q (CPU_INDR[6]));
  DFRRQST_X2 \CPU_Data_Path_INDR_reg[7] (.RN (RST), .C (CLK), .D
       (n_720), .Q (CPU_INDR[7]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[0] (.RN (RST), .C (CLK), .D
       (n_470), .Q (CPU_Data_Path_in_alu[0]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[10] (.RN (RST), .C (CLK), .D
       (n_465), .Q (CPU_Data_Path_in_alu[10]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[11] (.RN (RST), .C (CLK), .D
       (n_464), .Q (CPU_Data_Path_in_alu[11]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[12] (.RN (RST), .C (CLK), .D
       (n_463), .Q (CPU_Data_Path_in_alu[12]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[13] (.RN (RST), .C (CLK), .D
       (n_469), .Q (CPU_Data_Path_in_alu[13]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[14] (.RN (RST), .C (CLK), .D
       (n_462), .Q (CPU_Data_Path_in_alu[14]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[15] (.RN (RST), .C (CLK), .D
       (n_468), .Q (CPU_Data_Path_in_alu[15]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[1] (.RN (RST), .C (CLK), .D
       (n_459), .Q (CPU_Data_Path_in_alu[1]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[2] (.RN (RST), .C (CLK), .D
       (n_461), .Q (CPU_Data_Path_in_alu[2]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[3] (.RN (RST), .C (CLK), .D
       (n_471), .Q (CPU_Data_Path_in_alu[3]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[4] (.RN (RST), .C (CLK), .D
       (n_474), .Q (CPU_Data_Path_in_alu[4]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[5] (.RN (RST), .C (CLK), .D
       (n_472), .Q (CPU_Data_Path_in_alu[5]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[6] (.RN (RST), .C (CLK), .D
       (n_473), .Q (CPU_Data_Path_in_alu[6]));
  DFRRQST_X2 \CPU_Data_Path_in_alu_reg[7] (.RN (RST), .C (CLK), .D
       (n_475), .Q (CPU_Data_Path_in_alu[7]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[8] (.RN (RST), .C (CLK), .D
       (n_458), .Q (CPU_Data_Path_in_alu[8]));
  DFRRQST_X1 \CPU_Data_Path_in_alu_reg[9] (.RN (RST), .C (CLK), .D
       (n_457), .Q (CPU_Data_Path_in_alu[9]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[0] (.RN (RST), .C (CLK), .D
       (n_560), .Q (CPU_PC[0]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[1] (.RN (RST), .C (CLK), .D
       (n_558), .Q (CPU_PC[1]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[2] (.RN (RST), .C (CLK), .D
       (n_614), .Q (CPU_PC[2]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[3] (.RN (RST), .C (CLK), .D
       (n_642), .Q (CPU_PC[3]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[4] (.RN (RST), .C (CLK), .D
       (n_613), .Q (CPU_PC[4]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[5] (.RN (RST), .C (CLK), .D
       (n_632), .Q (CPU_PC[5]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[6] (.RN (RST), .C (CLK), .D
       (n_633), .Q (CPU_PC[6]));
  DFRRQST_X2 \CPU_Data_Path_reg_pc_reg[7] (.RN (RST), .C (CLK), .D
       (n_648), .Q (CPU_PC[7]));
  DFRRQST_X2 \PORT_OUT_reg[0] (.RN (RST), .C (CLK), .D (n_263), .Q
       (PORT_OUT[0]));
  DFRRQST_X2 \PORT_OUT_reg[1] (.RN (RST), .C (CLK), .D (n_262), .Q
       (PORT_OUT[1]));
  DFRRQST_X2 \PORT_OUT_reg[2] (.RN (RST), .C (CLK), .D (n_256), .Q
       (PORT_OUT[2]));
  DFRRQST_X2 \PORT_OUT_reg[3] (.RN (RST), .C (CLK), .D (n_257), .Q
       (PORT_OUT[3]));
  DFRRQST_X2 \PORT_OUT_reg[4] (.RN (RST), .C (CLK), .D (n_259), .Q
       (PORT_OUT[4]));
  DFRRQST_X2 \PORT_OUT_reg[5] (.RN (RST), .C (CLK), .D (n_258), .Q
       (PORT_OUT[5]));
  DFRRQST_X2 \PORT_OUT_reg[6] (.RN (RST), .C (CLK), .D (n_260), .Q
       (PORT_OUT[6]));
  DFRRQST_X2 \PORT_OUT_reg[7] (.RN (RST), .C (CLK), .D (n_261), .Q
       (PORT_OUT[7]));
  AO32ST_X2 g26343(.A (n_815), .B (n_568), .C (PROG), .D
       (BOOTLOADER_INTERFACE_tmp[5]), .E (n_63), .Q (n_842));
  MU2ST_X2 g26344(.IN0 (boot_data[0]), .IN1 (BOOTLOADER_wdata[0]), .S
       (n_32), .Q (n_841));
  MU2ST_X2 g26345(.IN0 (boot_data[10]), .IN1 (BOOTLOADER_wdata[10]), .S
       (n_31), .Q (n_840));
  MU2ST_X2 g26346(.IN0 (boot_data[11]), .IN1 (BOOTLOADER_wdata[11]), .S
       (n_32), .Q (n_839));
  MU2ST_X2 g26347(.IN0 (boot_data[12]), .IN1 (BOOTLOADER_wdata[12]), .S
       (n_31), .Q (n_838));
  MU2ST_X2 g26348(.IN0 (boot_data[13]), .IN1 (BOOTLOADER_wdata[13]), .S
       (n_31), .Q (n_837));
  MU2ST_X2 g26349(.IN0 (boot_data[14]), .IN1 (BOOTLOADER_wdata[14]), .S
       (n_32), .Q (n_836));
  MU2ST_X2 g26350(.IN0 (boot_data[15]), .IN1 (BOOTLOADER_wdata[15]), .S
       (n_32), .Q (n_835));
  MU2ST_X2 g26351(.IN0 (boot_data[2]), .IN1 (BOOTLOADER_wdata[2]), .S
       (n_32), .Q (n_834));
  MU2ST_X2 g26352(.IN0 (boot_data[3]), .IN1 (BOOTLOADER_wdata[3]), .S
       (n_32), .Q (n_833));
  MU2ST_X2 g26353(.IN0 (boot_data[1]), .IN1 (BOOTLOADER_wdata[1]), .S
       (n_32), .Q (n_832));
  MU2ST_X2 g26354(.IN0 (boot_data[4]), .IN1 (BOOTLOADER_wdata[4]), .S
       (n_31), .Q (n_831));
  MU2ST_X2 g26355(.IN0 (boot_data[5]), .IN1 (BOOTLOADER_wdata[5]), .S
       (n_32), .Q (n_830));
  MU2ST_X2 g26356(.IN0 (boot_data[6]), .IN1 (BOOTLOADER_wdata[6]), .S
       (n_31), .Q (n_829));
  MU2ST_X2 g26357(.IN0 (boot_data[7]), .IN1 (BOOTLOADER_wdata[7]), .S
       (n_31), .Q (n_828));
  MU2ST_X2 g26358(.IN0 (boot_data[8]), .IN1 (BOOTLOADER_wdata[8]), .S
       (n_31), .Q (n_827));
  MU2ST_X2 g26359(.IN0 (boot_data[9]), .IN1 (BOOTLOADER_wdata[9]), .S
       (n_31), .Q (n_826));
  MU2ST_X2 g26360(.IN0 (BOOTLOADER_wdata[0]), .IN1 (boot_addr[0]), .S
       (n_816), .Q (n_825));
  MU2ST_X2 g26361(.IN0 (BOOTLOADER_wdata[1]), .IN1 (boot_addr[1]), .S
       (n_816), .Q (n_824));
  MU2ST_X2 g26362(.IN0 (BOOTLOADER_wdata[3]), .IN1 (boot_addr[3]), .S
       (n_816), .Q (n_823));
  MU2ST_X2 g26363(.IN0 (BOOTLOADER_wdata[2]), .IN1 (boot_addr[2]), .S
       (n_816), .Q (n_822));
  MU2ST_X2 g26364(.IN0 (BOOTLOADER_wdata[4]), .IN1 (boot_addr[4]), .S
       (n_816), .Q (n_821));
  MU2ST_X2 g26365(.IN0 (BOOTLOADER_wdata[5]), .IN1 (boot_addr[5]), .S
       (n_816), .Q (n_820));
  MU2ST_X2 g26366(.IN0 (BOOTLOADER_wdata[6]), .IN1 (boot_addr[6]), .S
       (n_816), .Q (n_819));
  MU2ST_X2 g26367(.IN0 (BOOTLOADER_wdata[7]), .IN1 (boot_addr[7]), .S
       (n_816), .Q (n_818));
  MU2ST_X2 g26368(.IN0 (BOOTLOADER_INTERFACE_pwrite_o_tmp), .IN1
       (n_815), .S (PROG), .Q (n_817));
  NA5I4ST_X1 g26370(.AN (n_814), .BN (n_804), .CN (n_800), .DN (n_36),
       .E (n_455), .Q (n_816));
  NA6I5ST_X1 g26371(.AN (n_813), .BN (n_800), .CN (n_804), .DN (n_794),
       .EN (n_787), .F (n_455), .Q (n_815));
  NA5I4ST_X1 g26372(.AN (n_794), .BN (n_787), .CN (n_781), .DN (n_710),
       .E (n_812), .Q (n_814));
  NA5I4ST_X1 g26373(.AN (n_781), .BN (n_710), .CN (n_685), .DN (n_667),
       .E (n_811), .Q (n_813));
  NO6I2ST_X2 g26374(.AN (n_810), .BN (n_502), .C (n_685), .D (n_667),
       .E (n_622), .F (n_568), .Q (n_812));
  NO4I2ST_X1 g26375(.AN (n_810), .BN (n_568), .C (n_502), .D (n_622),
       .Q (n_811));
  NO4ST_X1 g26376(.A (n_766), .B (n_769), .C (n_772), .D (n_809), .Q
       (n_810));
  NA5I4ST_X1 g26377(.AN (n_775), .BN (n_760), .CN (n_757), .DN (n_754),
       .E (n_808), .Q (n_809));
  NO4ST_X1 g26378(.A (n_724), .B (n_741), .C (n_763), .D (n_806), .Q
       (n_808));
  MU2ST_X2 g26380(.IN0 (n_804), .IN1 (BOOTLOADER_INTERFACE_tmp[31]), .S
       (n_38), .Q (n_807));
  NA5I4ST_X1 g26382(.AN (n_803), .BN (n_797), .CN (n_749), .DN (n_735),
       .E (n_791), .Q (n_806));
  MU2ST_X2 g26383(.IN0 (n_803), .IN1 (BOOTLOADER_INTERFACE_tmp[30]), .S
       (n_39), .Q (n_805));
  EO2ST_X1 g26384(.A (BOOTLOADER_INTERFACE_tmp[31]), .B (n_802), .Q
       (n_804));
  HAST_X2 g26386(.A (BOOTLOADER_INTERFACE_tmp[30]), .B (n_799), .CO
       (n_802), .S (n_803));
  MU2ST_X2 g26387(.IN0 (n_800), .IN1 (BOOTLOADER_INTERFACE_tmp[29]), .S
       (n_40), .Q (n_801));
  HAST_X2 g26389(.A (BOOTLOADER_INTERFACE_tmp[29]), .B (n_796), .CO
       (n_799), .S (n_800));
  MU2ST_X2 g26390(.IN0 (n_797), .IN1 (BOOTLOADER_INTERFACE_tmp[28]), .S
       (n_41), .Q (n_798));
  HAST_X2 g26392(.A (BOOTLOADER_INTERFACE_tmp[28]), .B (n_793), .CO
       (n_796), .S (n_797));
  MU2ST_X2 g26393(.IN0 (n_794), .IN1 (BOOTLOADER_INTERFACE_tmp[27]), .S
       (n_42), .Q (n_795));
  HAST_X2 g26395(.A (BOOTLOADER_INTERFACE_tmp[27]), .B (n_789), .CO
       (n_793), .S (n_794));
  MU2ST_X2 g26396(.IN0 (n_790), .IN1 (BOOTLOADER_INTERFACE_tmp[26]), .S
       (n_63), .Q (n_792));
  NO3ST_X1 g26397(.A (n_778), .B (n_784), .C (n_790), .Q (n_791));
  HAST_X2 g26399(.A (BOOTLOADER_INTERFACE_tmp[26]), .B (n_786), .CO
       (n_789), .S (n_790));
  MU2ST_X2 g26400(.IN0 (n_787), .IN1 (BOOTLOADER_INTERFACE_tmp[25]), .S
       (n_36), .Q (n_788));
  HAST_X2 g26402(.A (BOOTLOADER_INTERFACE_tmp[25]), .B (n_783), .CO
       (n_786), .S (n_787));
  MU2ST_X2 g26403(.IN0 (n_784), .IN1 (BOOTLOADER_INTERFACE_tmp[24]), .S
       (n_37), .Q (n_785));
  HAST_X2 g26405(.A (BOOTLOADER_INTERFACE_tmp[24]), .B (n_780), .CO
       (n_783), .S (n_784));
  MU2ST_X2 g26406(.IN0 (n_781), .IN1 (BOOTLOADER_INTERFACE_tmp[23]), .S
       (n_38), .Q (n_782));
  HAST_X2 g26408(.A (BOOTLOADER_INTERFACE_tmp[23]), .B (n_777), .CO
       (n_780), .S (n_781));
  MU2ST_X2 g26409(.IN0 (n_778), .IN1 (BOOTLOADER_INTERFACE_tmp[22]), .S
       (n_39), .Q (n_779));
  HAST_X2 g26411(.A (BOOTLOADER_INTERFACE_tmp[22]), .B (n_774), .CO
       (n_777), .S (n_778));
  MU2ST_X2 g26412(.IN0 (n_775), .IN1 (BOOTLOADER_INTERFACE_tmp[21]), .S
       (n_40), .Q (n_776));
  HAST_X2 g26414(.A (BOOTLOADER_INTERFACE_tmp[21]), .B (n_771), .CO
       (n_774), .S (n_775));
  MU2ST_X2 g26415(.IN0 (n_772), .IN1 (BOOTLOADER_INTERFACE_tmp[20]), .S
       (n_41), .Q (n_773));
  HAST_X2 g26417(.A (BOOTLOADER_INTERFACE_tmp[20]), .B (n_768), .CO
       (n_771), .S (n_772));
  MU2ST_X2 g26418(.IN0 (n_769), .IN1 (BOOTLOADER_INTERFACE_tmp[19]), .S
       (n_42), .Q (n_770));
  HAST_X2 g26420(.A (BOOTLOADER_INTERFACE_tmp[19]), .B (n_765), .CO
       (n_768), .S (n_769));
  MU2ST_X2 g26421(.IN0 (n_766), .IN1 (BOOTLOADER_INTERFACE_tmp[18]), .S
       (n_63), .Q (n_767));
  HAST_X2 g26423(.A (BOOTLOADER_INTERFACE_tmp[18]), .B (n_762), .CO
       (n_765), .S (n_766));
  MU2ST_X2 g26424(.IN0 (n_763), .IN1 (BOOTLOADER_INTERFACE_tmp[17]), .S
       (n_36), .Q (n_764));
  HAST_X2 g26426(.A (BOOTLOADER_INTERFACE_tmp[17]), .B (n_759), .CO
       (n_762), .S (n_763));
  MU2ST_X2 g26427(.IN0 (n_760), .IN1 (BOOTLOADER_INTERFACE_tmp[16]), .S
       (n_37), .Q (n_761));
  HAST_X2 g26429(.A (BOOTLOADER_INTERFACE_tmp[16]), .B (n_756), .CO
       (n_759), .S (n_760));
  MU2ST_X2 g26430(.IN0 (n_757), .IN1 (BOOTLOADER_INTERFACE_tmp[15]), .S
       (n_38), .Q (n_758));
  HAST_X2 g26432(.A (BOOTLOADER_INTERFACE_tmp[15]), .B (n_753), .CO
       (n_756), .S (n_757));
  MU2ST_X2 g26433(.IN0 (n_754), .IN1 (BOOTLOADER_INTERFACE_tmp[14]), .S
       (n_39), .Q (n_755));
  HAST_X2 g26435(.A (BOOTLOADER_INTERFACE_tmp[14]), .B (n_748), .CO
       (n_753), .S (n_754));
  MU2ST_X2 g26437(.IN0 (n_749), .IN1 (BOOTLOADER_INTERFACE_tmp[13]), .S
       (n_40), .Q (n_752));
  ON221ST_X1 g26438(.A (n_548), .B (n_225), .C (n_205), .D (n_294), .E
       (n_750), .Q (n_751));
  AN221ST_X1 g26440(.A (n_410), .B (CPU_Data_Path_in_alu[15]), .C
       (n_57), .D (n_93), .E (n_745), .Q (n_750));
  HAST_X2 g26441(.A (BOOTLOADER_INTERFACE_tmp[13]), .B (n_740), .CO
       (n_748), .S (n_749));
  MU2ST_X2 g26443(.IN0 (n_741), .IN1 (BOOTLOADER_INTERFACE_tmp[12]), .S
       (n_41), .Q (n_747));
  ON221ST_X1 g26445(.A (n_713), .B (n_55), .C (n_241), .D (n_294), .E
       (n_742), .Q (n_746));
  ON221ST_X1 g26446(.A (n_522), .B (n_406), .C (n_359), .D (n_537), .E
       (n_743), .Q (n_745));
  NA3ST_X1 g26448(.A (n_577), .B (n_653), .C (n_736), .Q (n_744));
  AN221ST_X1 g26449(.A (n_616), .B (n_23), .C (n_391), .D
       (CPU_ACC[15]), .E (n_739), .Q (n_743));
  AN211ST_X1 g26450(.A (n_411), .B (CPU_Data_Path_in_alu[14]), .C
       (n_737), .D (n_652), .Q (n_742));
  HAST_X2 g26451(.A (BOOTLOADER_INTERFACE_tmp[12]), .B (n_734), .CO
       (n_740), .S (n_741));
  ON22ST_X1 g26452(.A (n_732), .B (n_25), .C (n_725), .D (n_55), .Q
       (n_739));
  MU2ST_X2 g26453(.IN0 (n_735), .IN1 (BOOTLOADER_INTERFACE_tmp[11]), .S
       (n_42), .Q (n_738));
  ON222ST_X1 g26455(.A (n_726), .B (n_25), .C (n_59), .D (n_75), .E
       (n_334), .F (CPU_ACC[14]), .Q (n_737));
  AN221ST_X1 g26456(.A (n_702), .B (n_24), .C (n_295), .D (n_242), .E
       (n_731), .Q (n_736));
  HAST_X2 g26457(.A (BOOTLOADER_INTERFACE_tmp[11]), .B (n_723), .CO
       (n_734), .S (n_735));
  NA3ST_X1 g26459(.A (n_576), .B (n_649), .C (n_730), .Q (n_733));
  EO2ST_X1 g26460(.A (n_205), .B (n_727), .Q (n_732));
  ON222ST_X1 g26462(.A (n_714), .B (n_296), .C (n_59), .D (n_106), .E
       (n_334), .F (CPU_ACC[13]), .Q (n_731));
  AN221ST_X1 g26463(.A (n_692), .B (n_24), .C (n_295), .D (n_246), .E
       (n_722), .Q (n_730));
  MU2ST_X2 g26464(.IN0 (n_724), .IN1 (BOOTLOADER_INTERFACE_tmp[10]), .S
       (n_63), .Q (n_729));
  NA3I1ST_X1 g26466(.AN (n_721), .B (n_422), .C (n_575), .Q (n_728));
  AN21ST_X1 g26467(.A (n_717), .B (n_129), .C (n_160), .Q (n_727));
  EN2ST_X1 g26468(.A (n_241), .B (n_717), .Q (n_726));
  EO2ST_X1 g26469(.A (n_205), .B (n_718), .Q (n_725));
  HAST_X2 g26470(.A (BOOTLOADER_INTERFACE_tmp[10]), .B (n_709), .CO
       (n_723), .S (n_724));
  ON221ST_X1 g26473(.A (n_548), .B (n_354), .C (n_43), .D (n_334), .E
       (n_716), .Q (n_722));
  ON321ST_X1 g26474(.A (n_355), .B (n_58), .C (n_515), .D (n_359), .E
       (n_539), .F (n_712), .Q (n_721));
  MU2ST_X2 g26475(.IN0 (n_711), .IN1 (CPU_INDR[7]), .S (n_371), .Q
       (n_720));
  ON311ST_X1 g26476(.A (n_515), .B (n_58), .C (n_324), .D (n_705), .E
       (n_607), .Q (n_719));
  ON22ST_X1 g26477(.A (n_707), .B (n_146), .C (n_103), .D (n_75), .Q
       (n_718));
  ON22ST_X1 g26478(.A (n_706), .B (n_114), .C
       (CPU_Data_Path_in_alu[13]), .D (n_106), .Q (n_717));
  AN22ST_X1 g26479(.A (n_703), .B (n_56), .C (n_403), .D
       (CPU_Data_Path_in_alu[12]), .Q (n_716));
  MU2ST_X2 g26480(.IN0 (n_710), .IN1 (BOOTLOADER_INTERFACE_tmp[9]), .S
       (n_36), .Q (n_715));
  EN2ST_X1 g26481(.A (n_242), .B (n_706), .Q (n_714));
  EN2ST_X1 g26482(.A (n_241), .B (n_707), .Q (n_713));
  AN221ST_X1 g26484(.A (n_674), .B (n_285), .C (n_404), .D
       (CPU_Data_Path_in_alu[11]), .E (n_704), .Q (n_712));
  AO222ST_X2 g26485(.A (n_348), .B (gm_Q_tmp[7]), .C
       (CPU_Data_Path_n_7530), .D (n_691), .E (n_346), .F (PORT_IN[7]),
       .Q (n_711));
  HAST_X2 g26486(.A (BOOTLOADER_INTERFACE_tmp[9]), .B (n_684), .CO
       (n_709), .S (n_710));
  NA3ST_X1 g26489(.A (n_572), .B (n_578), .C (n_700), .Q (n_708));
  AN21ST_X1 g26490(.A (n_961), .B (n_166), .C (n_156), .Q (n_707));
  AN21ST_X1 g26491(.A (n_695), .B (n_158), .C (n_142), .Q (n_706));
  AN21ST_X1 g26492(.A (n_657), .B (n_285), .C (n_701), .Q (n_705));
  ON22ST_X1 g26493(.A (n_693), .B (n_296), .C (n_30), .D (CPU_ACC[11]),
       .Q (n_704));
  EN2ST_X1 g26494(.A (n_246), .B (n_695), .Q (n_703));
  EO2ST_X1 g26495(.A (n_242), .B (n_961), .Q (n_702));
  ON221ST_X1 g26497(.A (n_512), .B (n_379), .C (CPU_ACC[10]), .D
       (n_30), .E (n_694), .Q (n_701));
  AN321ST_X1 g26498(.A (n_545), .B (n_23), .C (n_210), .D (n_635), .E
       (n_285), .F (n_687), .Q (n_700));
  MU2ST_X2 g26499(.IN0 (n_686), .IN1 (CPU_INDR[6]), .S (n_371), .Q
       (n_699));
  MU2ST_X2 g26500(.IN0 (n_685), .IN1 (BOOTLOADER_INTERFACE_tmp[8]), .S
       (n_37), .Q (n_698));
  NA4ST_X1 g26503(.A (n_369), .B (n_574), .C (n_626), .D (n_671), .Q
       (n_697));
  ON21ST_X1 g26505(.A (n_682), .B (n_149), .C (n_123), .Q (n_695));
  AN22ST_X1 g26506(.A (n_675), .B (n_56), .C (n_412), .D
       (CPU_Data_Path_in_alu[10]), .Q (n_694));
  EN2ST_X1 g26507(.A (n_232), .B (n_682), .Q (n_693));
  EO2ST_X1 g26508(.A (n_246), .B (n_962), .Q (n_692));
  EO3ST_X1 g26509(.A (CPU_INDR[7]), .B (CPU_OPERAND[7]), .C (n_668), .Q
       (n_691));
  AO211ST_X2 g26514(.A (n_370), .B (CPU_ACC[1]), .C (n_670), .D
       (n_612), .Q (n_690));
  ON221ST_X1 g26516(.A (n_520), .B (n_406), .C (n_150), .D (n_157), .E
       (n_679), .Q (n_688));
  ON221ST_X1 g26517(.A (n_512), .B (n_377), .C (CPU_ACC[9]), .D (n_30),
       .E (n_678), .Q (n_687));
  AO222ST_X2 g26518(.A (n_348), .B (gm_Q_tmp[6]), .C
       (CPU_Data_Path_n_7530), .D (n_669), .E (n_346), .F (PORT_IN[6]),
       .Q (n_686));
  HAST_X2 g26519(.A (BOOTLOADER_INTERFACE_tmp[8]), .B (n_666), .CO
       (n_684), .S (n_685));
  NA5I4ST_X1 g26521(.AN (n_639), .BN (n_611), .CN (n_480), .DN (n_374),
       .E (n_602), .Q (n_681));
  NA5I4ST_X1 g26522(.AN (n_583), .BN (n_446), .CN (n_421), .DN (n_375),
       .E (n_656), .Q (n_680));
  AN21ST_X1 g26524(.A (n_662), .B (n_124), .C (n_148), .Q (n_682));
  AN221ST_X1 g26525(.A (n_550), .B (n_24), .C (n_295), .D (n_244), .E
       (n_665), .Q (n_679));
  AN22ST_X1 g26526(.A (n_658), .B (n_56), .C (n_409), .D
       (CPU_Data_Path_in_alu[9]), .Q (n_678));
  MU2ST_X2 g26527(.IN0 (n_660), .IN1 (CPU_INDR[5]), .S (n_371), .Q
       (n_677));
  MU2ST_X2 g26528(.IN0 (n_667), .IN1 (BOOTLOADER_INTERFACE_tmp[7]), .S
       (n_38), .Q (n_676));
  EN2ST_X1 g26529(.A (n_253), .B (n_662), .Q (n_675));
  EO2ST_X1 g26530(.A (n_232), .B (n_963), .Q (n_674));
  NA3ST_X1 g26533(.A (n_382), .B (n_591), .C (n_659), .Q (n_673));
  AN221ST_X1 g26535(.A (n_636), .B (n_56), .C (n_598), .D (n_24), .E
       (n_588), .Q (n_671));
  ON211ST_X1 g26536(.A (n_334), .B (CPU_ACC[1]), .C (n_650), .D
       (n_628), .Q (n_670));
  FAST_X2 g26537(.A (CPU_OPERAND[6]), .B (CPU_INDR[6]), .CI (n_623),
       .CO (n_668), .S (n_669));
  HAST_X2 g26538(.A (BOOTLOADER_INTERFACE_tmp[7]), .B (n_621), .CO
       (n_666), .S (n_667));
  AO211ST_X2 g26543(.A (n_391), .B (CPU_ACC[7]), .C (n_637), .D
       (n_608), .Q (n_665));
  NA4I2ST_X1 g26544(.AN (n_641), .BN (n_600), .C (n_579), .D (n_590),
       .Q (n_664));
  ON221ST_X1 g26545(.A (n_520), .B (n_380), .C (n_147), .D (n_26), .E
       (n_651), .Q (n_661));
  ON21ST_X1 g26547(.A (n_644), .B (n_126), .C (n_152), .Q (n_662));
  AO222ST_X2 g26548(.A (n_348), .B (gm_Q_tmp[5]), .C
       (CPU_Data_Path_n_7530), .D (n_624), .E (n_346), .F (PORT_IN[5]),
       .Q (n_660));
  AN222ST_X1 g26549(.A (n_631), .B (n_343), .C (n_57), .D (n_97), .E
       (n_18), .F (CPU_ACC[0]), .Q (n_659));
  EN2ST_X1 g26550(.A (n_227), .B (n_643), .Q (n_658));
  EO2ST_X1 g26551(.A (n_253), .B (n_645), .Q (n_657));
  AN221ST_X1 g26553(.A (n_547), .B (n_1), .C (n_566), .D (CPU_ACC[3]),
       .E (n_638), .Q (n_656));
  ON221ST_X1 g26554(.A (n_505), .B (n_234), .C (n_381), .D (n_520), .E
       (n_640), .Q (n_655));
  AN221ST_X1 g26556(.A (n_617), .B (n_341), .C (n_53), .D (n_156), .E
       (n_593), .Q (n_653));
  ON221ST_X1 g26557(.A (n_615), .B (n_58), .C (n_358), .D (n_537), .E
       (n_556), .Q (n_652));
  AN221ST_X1 g26558(.A (n_434), .B (n_24), .C (n_295), .D (n_255), .E
       (n_634), .Q (n_651));
  OA222ST_X2 g26559(.A (n_604), .B (n_342), .C (n_25), .D (n_302), .E
       (n_521), .F (n_377), .Q (n_650));
  AN22ST_X1 g26560(.A (n_630), .B (n_341), .C (n_18), .D (n_43), .Q
       (n_649));
  AO221ST_X2 g26561(.A (n_494), .B (n_352), .C (n_1180), .D
       (CPU_OPERAND[7]), .E (n_627), .Q (n_648));
  MU2ST_X2 g26562(.IN0 (n_625), .IN1 (CPU_INDR[4]), .S (n_371), .Q
       (n_647));
  MU2ST_X2 g26563(.IN0 (n_622), .IN1 (BOOTLOADER_INTERFACE_tmp[6]), .S
       (n_39), .Q (n_646));
  INST_X4 g26564(.A (n_643), .Q (n_644));
  NA4ST_X1 g26567(.A (n_489), .B (n_507), .C (n_514), .D (n_596), .Q
       (n_642));
  ON211ST_X1 g26568(.A (n_30), .B (n_1055), .C (n_603), .D (n_553), .Q
       (n_641));
  AO21ST_X2 g26569(.A (CPU_Data_Path_in_alu[9]), .B (CPU_ACC[9]), .C
       (n_629), .Q (n_645));
  ON22ST_X1 g26570(.A (n_619), .B (n_144), .C
       (CPU_Data_Path_in_alu[8]), .D (n_44), .Q (n_643));
  AN211ST_X1 g26571(.A (n_531), .B (n_234), .C (n_609), .D (n_606), .Q
       (n_640));
  ON222ST_X1 g26572(.A (n_581), .B (n_342), .C (n_521), .D (n_376), .E
       (n_597), .F (n_83), .Q (n_639));
  ON222ST_X1 g26573(.A (n_582), .B (n_342), .C (n_521), .D (n_379), .E
       (n_597), .F (n_80), .Q (n_638));
  ON22ST_X1 g26574(.A (n_599), .B (n_25), .C (n_30), .D (n_17), .Q
       (n_637));
  EN2ST_X1 g26575(.A (n_230), .B (n_619), .Q (n_636));
  EN2ST_X1 g26576(.A (n_227), .B (n_620), .Q (n_635));
  AO211ST_X2 g26580(.A (n_18), .B (n_98), .C (n_610), .D (n_506), .Q
       (n_634));
  AO221ST_X2 g26581(.A (n_559), .B (n_353), .C (n_467), .D (CPU_PC[6]),
       .E (n_595), .Q (n_633));
  ON221ST_X1 g26582(.A (n_562), .B (n_322), .C (n_427), .D (n_491), .E
       (n_563), .Q (n_632));
  ON221ST_X1 g26583(.A (n_495), .B (n_405), .C (n_357), .D (n_518), .E
       (n_618), .Q (n_631));
  ON21ST_X1 g26584(.A (n_541), .B (n_71), .C (n_605), .Q (n_630));
  AN21ST_X1 g26585(.A (n_108), .B (n_85), .C (n_620), .Q (n_629));
  AN221ST_X1 g26586(.A (n_547), .B (n_2), .C (n_566), .D (CPU_ACC[2]),
       .E (n_423), .Q (n_628));
  ON221ST_X1 g26587(.A (n_486), .B (n_552), .C (n_291), .D (n_444), .E
       (n_525), .Q (n_627));
  AN321ST_X1 g26588(.A (n_545), .B (n_23), .C (n_155), .D (n_18), .E
       (n_86), .F (n_554), .Q (n_626));
  AO222ST_X2 g26589(.A (n_348), .B (gm_Q_tmp[4]), .C
       (CPU_Data_Path_n_7530), .D (n_570), .E (n_346), .F (PORT_IN[4]),
       .Q (n_625));
  FAST_X2 g26590(.A (CPU_OPERAND[5]), .B (CPU_INDR[5]), .CI (n_569),
       .CO (n_623), .S (n_624));
  HAST_X2 g26591(.A (BOOTLOADER_INTERFACE_tmp[6]), .B (n_567), .CO
       (n_621), .S (n_622));
  OA221ST_X2 g26592(.A (n_543), .B (n_80), .C (n_83), .D (n_544), .E
       (n_580), .Q (n_618));
  ON221ST_X1 g26593(.A (n_541), .B (n_106), .C (n_71), .D (n_542), .E
       (n_587), .Q (n_617));
  ON221ST_X1 g26594(.A (n_541), .B (n_93), .C (n_75), .D (n_542), .E
       (n_585), .Q (n_616));
  OA221ST_X2 g26595(.A (n_541), .B (n_75), .C (n_106), .D (n_542), .E
       (n_586), .Q (n_615));
  ON221ST_X1 g26596(.A (n_533), .B (n_279), .C (n_372), .D (n_491), .E
       (n_535), .Q (n_614));
  AO221ST_X2 g26597(.A (n_534), .B (n_276), .C (n_450), .D (CPU_PC[4]),
       .E (n_594), .Q (n_613));
  AN21ST_X1 g26598(.A (n_565), .B (n_168), .C (n_137), .Q (n_620));
  AN22ST_X1 g26599(.A (n_564), .B (n_117), .C (n_92), .D (n_17), .Q
       (n_619));
  ON221ST_X1 g26600(.A (n_55), .B (n_303), .C (n_128), .D (n_26), .E
       (n_584), .Q (n_612));
  ON221ST_X1 g26601(.A (n_435), .B (n_231), .C (n_355), .D (n_539), .E
       (n_424), .Q (n_611));
  ON221ST_X1 g26602(.A (n_548), .B (n_357), .C (n_354), .D (n_546), .E
       (n_592), .Q (n_610));
  AO221ST_X2 g26603(.A (n_547), .B (n_326), .C (n_388), .D
       (CPU_Data_Path_in_alu[5]), .E (n_573), .Q (n_609));
  ON221ST_X1 g26604(.A (n_548), .B (n_363), .C (n_225), .D (n_546), .E
       (n_589), .Q (n_608));
  AN221ST_X1 g26605(.A (n_536), .B (n_328), .C (n_18), .D (n_90), .E
       (n_571), .Q (n_607));
  ON222ST_X1 g26606(.A (n_546), .B (n_323), .C (n_59), .D (n_84), .E
       (n_30), .F (CPU_ACC[5]), .Q (n_606));
  OA222ST_X2 g26607(.A (n_543), .B (n_46), .C (n_544), .D (n_85), .E
       (n_542), .F (n_45), .Q (n_605));
  OA222ST_X2 g26608(.A (n_543), .B (n_83), .C (n_544), .D (n_99), .E
       (n_541), .F (n_100), .Q (n_604));
  AN32ST_X1 g26609(.A (n_545), .B (n_343), .C (n_207), .D (n_295), .E
       (n_229), .Q (n_603));
  AN22ST_X1 g26610(.A (n_547), .B (n_364), .C (n_566), .D (n_98), .Q
       (n_602));
  MU2ST_X2 g26611(.IN0 (n_557), .IN1 (CPU_INDR[3]), .S (n_371), .Q
       (n_601));
  ON22ST_X1 g26612(.A (n_551), .B (n_296), .C (n_520), .D (n_378), .Q
       (n_600));
  EO2ST_X1 g26613(.A (n_244), .B (n_564), .Q (n_599));
  EN2ST_X1 g26614(.A (n_230), .B (n_565), .Q (n_598));
  NA2I1ST_X1 g26617(.AN (n_321), .B (n_561), .Q (n_596));
  ON321ST_X1 g26618(.A (CPU_PC[6]), .B (n_291), .C (n_396), .D (n_451),
       .E (n_491), .F (n_555), .Q (n_595));
  AN21ST_X1 g26619(.A (n_540), .B (n_343), .C (n_370), .Q (n_597));
  ON221ST_X1 g26620(.A (n_514), .B (n_276), .C (n_291), .D (n_182), .E
       (n_509), .Q (n_594));
  ON22ST_X1 g26621(.A (n_548), .B (n_323), .C (n_386), .D (n_87), .Q
       (n_593));
  AN22ST_X1 g26622(.A (n_547), .B (n_332), .C (n_388), .D
       (CPU_Data_Path_in_alu[4]), .Q (n_592));
  AN32ST_X1 g26623(.A (n_519), .B (n_164), .C (n_155), .D (n_388), .E
       (CPU_Data_Path_in_alu[0]), .Q (n_591));
  AN22ST_X1 g26624(.A (n_549), .B (n_1), .C (n_6), .D
       (CPU_Data_Path_in_alu[6]), .Q (n_590));
  AN22ST_X1 g26625(.A (n_547), .B (n_338), .C (n_6), .D
       (CPU_Data_Path_in_alu[7]), .Q (n_589));
  ON22ST_X1 g26626(.A (n_539), .B (n_367), .C (n_386), .D (n_73), .Q
       (n_588));
  OA22ST_X2 g26627(.A (n_543), .B (n_45), .C (n_544), .D (n_46), .Q
       (n_587));
  OA22ST_X2 g26628(.A (n_543), .B (n_71), .C (n_544), .D (n_45), .Q
       (n_586));
  OA22ST_X2 g26629(.A (n_543), .B (n_106), .C (n_544), .D (n_71), .Q
       (n_585));
  AN32ST_X1 g26630(.A (n_516), .B (n_23), .C (n_210), .D (n_344), .E
       (n_175), .Q (n_584));
  ON22ST_X1 g26631(.A (n_539), .B (n_324), .C (n_399), .D (n_228), .Q
       (n_583));
  OA22ST_X2 g26632(.A (n_543), .B (n_99), .C (n_544), .D (n_84), .Q
       (n_582));
  OA22ST_X2 g26633(.A (n_543), .B (n_84), .C (n_544), .D (n_105), .Q
       (n_581));
  OA22ST_X2 g26634(.A (n_541), .B (n_97), .C (n_542), .D (n_100), .Q
       (n_580));
  AN22ST_X1 g26635(.A (n_547), .B (n_335), .C (n_391), .D (CPU_ACC[6]),
       .Q (n_579));
  AN22ST_X1 g26636(.A (n_536), .B (n_336), .C (n_18), .D (CPU_ACC[9]),
       .Q (n_578));
  OA22ST_X2 g26637(.A (n_522), .B (n_381), .C (n_537), .D (n_365), .Q
       (n_577));
  OA22ST_X2 g26638(.A (n_522), .B (n_380), .C (n_537), .D (n_367), .Q
       (n_576));
  OA22ST_X2 g26639(.A (n_512), .B (n_376), .C (n_537), .D (n_333), .Q
       (n_575));
  AN22ST_X1 g26640(.A (n_536), .B (n_339), .C (n_53), .D (n_137), .Q
       (n_574));
  AO22ST_X2 g26641(.A (n_549), .B (n_2), .C (n_53), .D (n_122), .Q
       (n_573));
  AN22ST_X1 g26642(.A (n_538), .B (n_366), .C (n_11), .D (n_227), .Q
       (n_572));
  ON22ST_X1 g26643(.A (n_539), .B (n_358), .C (n_294), .D (n_252), .Q
       (n_571));
  FAST_X2 g26644(.A (CPU_OPERAND[4]), .B (CPU_INDR[4]), .CI (n_499),
       .CO (n_569), .S (n_570));
  HAST_X2 g26645(.A (BOOTLOADER_INTERFACE_tmp[5]), .B (n_501), .CO
       (n_567), .S (n_568));
  NO2I1ST_X1 g26648(.AN (n_7), .B (n_542), .Q (n_566));
  AN221ST_X1 g26649(.A (n_1180), .B (CPU_OPERAND[5]), .C (n_450), .D
       (CPU_PC[5]), .E (n_527), .Q (n_563));
  NO2ST_X1 g26650(.A (n_526), .B (n_534), .Q (n_562));
  ON221ST_X1 g26651(.A (n_486), .B (n_419), .C (n_279), .D (n_491), .E
       (n_533), .Q (n_561));
  AO221ST_X2 g26652(.A (n_485), .B (n_206), .C (n_1180), .D
       (CPU_OPERAND[0]), .E (n_528), .Q (n_560));
  ON21ST_X1 g26653(.A (n_511), .B (n_176), .C (n_150), .Q (n_565));
  ON22ST_X1 g26654(.A (n_964), .B (n_116), .C
       (CPU_Data_Path_in_alu[6]), .D (n_105), .Q (n_564));
  AO221ST_X2 g26655(.A (n_492), .B (n_427), .C (n_485), .D (n_498), .E
       (n_494), .Q (n_559));
  ON221ST_X1 g26656(.A (n_491), .B (n_368), .C (n_1173), .D (n_493), .E
       (n_530), .Q (n_558));
  AO222ST_X2 g26657(.A (n_348), .B (gm_Q_tmp[3]), .C
       (CPU_Data_Path_n_7530), .D (n_500), .E (n_346), .F (PORT_IN[3]),
       .Q (n_557));
  OA21ST_X2 g26658(.A (n_522), .B (n_378), .C (n_532), .Q (n_556));
  AN21ST_X1 g26659(.A (n_1180), .B (CPU_OPERAND[6]), .C (n_529), .Q
       (n_555));
  ON22ST_X1 g26660(.A (n_512), .B (n_405), .C (n_294), .D (n_230), .Q
       (n_554));
  AN22ST_X1 g26661(.A (n_503), .B (n_24), .C (n_53), .D (n_131), .Q
       (n_553));
  EN2ST_X1 g26662(.A (n_513), .B (n_352), .Q (n_552));
  EN2ST_X1 g26663(.A (n_229), .B (n_964), .Q (n_551));
  EN2ST_X1 g26664(.A (n_244), .B (n_511), .Q (n_550));
  INST_X4 g26665(.A (n_549), .Q (n_548));
  INST_X2 g26666(.A (n_541), .Q (n_540));
  INST_X2 g26667(.A (n_539), .Q (n_538));
  INST_X3 g26668(.A (n_537), .Q (n_536));
  AND2ST_X2 g26669(.A (n_517), .B (n_343), .Q (n_549));
  NO2I1ST_X1 g26670(.AN (n_7), .B (n_518), .Q (n_547));
  NA2I1ST_X1 g26671(.AN (n_515), .B (n_343), .Q (n_546));
  NO2ST_X1 g26672(.A (CPU_Data_Path_in_alu[1]), .B (n_515), .Q (n_545));
  NA2ST_X1 g26673(.A (n_517), .B (n_49), .Q (n_544));
  NA2ST_X1 g26674(.A (n_517), .B (n_27), .Q (n_543));
  NA2ST_X1 g26675(.A (n_516), .B (CPU_Data_Path_in_alu[0]), .Q (n_542));
  NA2I1ST_X1 g26676(.AN (n_12), .B (n_516), .Q (n_541));
  NA2ST_X1 g26677(.A (n_517), .B (n_23), .Q (n_539));
  NA2I1ST_X1 g26678(.AN (n_518), .B (n_23), .Q (n_537));
  AN221ST_X1 g26679(.A (n_1180), .B (CPU_OPERAND[2]), .C (n_450), .D
       (CPU_PC[2]), .E (n_508), .Q (n_535));
  NA3I1ST_X1 g26680(.AN (n_512), .B (n_164), .C (n_207), .Q (n_532));
  ON221ST_X1 g26681(.A (n_481), .B (n_25), .C (n_55), .D (n_448), .E
       (n_294), .Q (n_531));
  ON21ST_X1 g26682(.A (n_491), .B (n_389), .C (n_493), .Q (n_534));
  AN221ST_X1 g26683(.A (n_1180), .B (CPU_OPERAND[1]), .C (n_450), .D
       (CPU_PC[1]), .E (n_504), .Q (n_530));
  AN21ST_X1 g26684(.A (n_492), .B (n_347), .C (n_494), .Q (n_533));
  NO3ST_X1 g26685(.A (n_498), .B (n_353), .C (n_486), .Q (n_529));
  ON222ST_X1 g26686(.A (n_484), .B (n_301), .C (n_449), .D (n_74), .E
       (n_291), .F (CPU_PC[0]), .Q (n_528));
  AO32ST_X2 g26687(.A (n_485), .B (n_322), .C (n_488), .D (n_394), .E
       (n_292), .Q (n_527));
  ON22ST_X1 g26688(.A (n_486), .B (n_488), .C (n_491), .D (n_277), .Q
       (n_526));
  AN22ST_X1 g26689(.A (n_492), .B (n_478), .C (n_467), .D (CPU_PC[7]),
       .Q (n_525));
  MU2ST_X2 g26690(.IN0 (n_490), .IN1 (CPU_INDR[2]), .S (n_371), .Q
       (n_524));
  MU2ST_X2 g26691(.IN0 (n_502), .IN1 (BOOTLOADER_INTERFACE_tmp[4]), .S
       (n_40), .Q (n_523));
  INST_X2 g26692(.A (n_520), .Q (n_519));
  NA2I1ST_X1 g26693(.AN (n_495), .B (n_341), .Q (n_522));
  NA2I1ST_X1 g26694(.AN (n_495), .B (n_343), .Q (n_521));
  NO2I1ST_X1 g26695(.AN (n_353), .B (n_498), .Q (n_513));
  NA2ST_X1 g26696(.A (n_497), .B (n_341), .Q (n_520));
  NA2ST_X1 g26697(.A (n_497), .B (CPU_Data_Path_in_alu[2]), .Q (n_518));
  NO2ST_X1 g26698(.A (CPU_Data_Path_in_alu[2]), .B (n_496), .Q (n_517));
  AND2ST_X2 g26699(.A (n_497), .B (n_164), .Q (n_516));
  NA2I1ST_X1 g26700(.AN (n_495), .B (n_20), .Q (n_515));
  NA2ST_X1 g26701(.A (n_492), .B (n_389), .Q (n_514));
  NA2I1ST_X1 g26702(.AN (n_342), .B (n_497), .Q (n_512));
  AN21ST_X1 g26703(.A (n_482), .B (n_172), .C (n_131), .Q (n_511));
  AN22ST_X1 g26705(.A (n_485), .B (n_487), .C (n_1180), .D
       (CPU_OPERAND[4]), .Q (n_509));
  AO22ST_X2 g26706(.A (n_485), .B (n_418), .C (n_1174), .D (n_292), .Q
       (n_508));
  AN32ST_X1 g26707(.A (n_485), .B (n_321), .C (n_419), .D (n_1170), .E
       (n_292), .Q (n_507));
  ON22ST_X1 g26708(.A (n_477), .B (n_296), .C (n_334), .D (CPU_ACC[4]),
       .Q (n_506));
  AN22ST_X1 g26709(.A (n_481), .B (n_56), .C (n_448), .D (n_285), .Q
       (n_505));
  AO22ST_X2 g26710(.A (n_485), .B (n_368), .C (n_292), .D (n_179), .Q
       (n_504));
  EO2ST_X1 g26711(.A (n_229), .B (n_482), .Q (n_503));
  HAST_X2 g26712(.A (BOOTLOADER_INTERFACE_tmp[4]), .B (n_455), .CO
       (n_501), .S (n_502));
  FAST_X2 g26713(.A (CPU_OPERAND[3]), .B (CPU_INDR[3]), .CI (n_452),
       .CO (n_499), .S (n_500));
  NA2I1ST_X1 g26715(.AN (n_322), .B (n_488), .Q (n_498));
  INST_X3 g26716(.A (n_496), .Q (n_497));
  NA2I1ST_X1 g26717(.AN (CPU_Data_Path_in_alu[3]), .B (n_483), .Q
       (n_496));
  NA2ST_X1 g26718(.A (n_483), .B (CPU_Data_Path_in_alu[3]), .Q (n_495));
  INST_X3 g26719(.A (n_494), .Q (n_493));
  NO2ST_X1 g26720(.A (PC_UF), .B (n_484), .Q (n_494));
  INST_X4 g26721(.A (n_492), .Q (n_491));
  NO2I1ST_X1 g26722(.AN (PC_UF), .B (n_484), .Q (n_492));
  AO222ST_X2 g26723(.A (n_348), .B (gm_Q_tmp[2]), .C
       (CPU_Data_Path_n_7530), .D (n_453), .E (n_346), .F (PORT_IN[2]),
       .Q (n_490));
  AN22ST_X1 g26724(.A (n_1180), .B (CPU_OPERAND[3]), .C (n_450), .D
       (CPU_PC[3]), .Q (n_489));
  HAST_X2 g26725(.A (n_432), .B (n_276), .CO (n_488), .S (n_487));
  INST_X4 g26739(.A (n_486), .Q (n_485));
  NO2I1ST_X1 g26744(.AN (n_231), .B (n_460), .Q (n_480));
  NA2ST_X1 g26745(.A (PC_OF), .B (n_466), .Q (n_486));
  NA2I1ST_X1 g26746(.AN (PC_OF), .B (n_466), .Q (n_484));
  NO4ST_X1 g26747(.A (CPU_Data_Path_in_alu[14]), .B
       (CPU_Data_Path_in_alu[11]), .C (CPU_Data_Path_in_alu[12]), .D
       (n_431), .Q (n_483));
  AO21ST_X2 g26748(.A (n_448), .B (n_177), .C (n_122), .Q (n_482));
  AN22ST_X1 g26749(.A (n_447), .B (n_120), .C (n_104), .D (CPU_ACC[4]),
       .Q (n_481));
  MU2ST_X2 g26750(.IN0 (n_454), .IN1 (BOOTLOADER_INTERFACE_tmp[3]), .S
       (n_41), .Q (n_479));
  EN2ST_X1 g26751(.A (n_352), .B (n_451), .Q (n_478));
  EO2ST_X1 g26752(.A (n_255), .B (n_447), .Q (n_477));
  ON221ST_X1 g26756(.A (n_416), .B (n_101), .C (n_92), .D (n_65), .E
       (n_437), .Q (n_475));
  ON221ST_X1 g26757(.A (n_416), .B (n_94), .C (n_104), .D (n_22), .E
       (n_440), .Q (n_474));
  ON221ST_X1 g26758(.A (n_416), .B (n_70), .C (n_69), .D (n_21), .E
       (n_438), .Q (n_473));
  ON221ST_X1 g26759(.A (n_416), .B (n_82), .C (n_77), .D (n_22), .E
       (n_439), .Q (n_472));
  ON221ST_X1 g26760(.A (n_416), .B (n_72), .C (n_68), .D (n_21), .E
       (n_441), .Q (n_471));
  ON221ST_X1 g26761(.A (n_416), .B (n_91), .C (n_107), .D (n_21), .E
       (n_443), .Q (n_470));
  AO221ST_X2 g26762(.A (n_417), .B (gm_Q_tmp[13]), .C (n_64), .D
       (CPU_Data_Path_in_alu[13]), .E (n_433), .Q (n_469));
  AO221ST_X2 g26763(.A (n_29), .B (gm_Q_tmp[15]), .C (n_64), .D
       (CPU_Data_Path_in_alu[15]), .E (n_433), .Q (n_468));
  AO221ST_X2 g26764(.A (n_29), .B (gm_Q_tmp[10]), .C (n_66), .D
       (CPU_Data_Path_in_alu[10]), .E (n_433), .Q (n_465));
  AO221ST_X2 g26765(.A (n_417), .B (gm_Q_tmp[11]), .C (n_66), .D
       (CPU_Data_Path_in_alu[11]), .E (n_433), .Q (n_464));
  AO221ST_X2 g26766(.A (n_29), .B (gm_Q_tmp[12]), .C (n_66), .D
       (CPU_Data_Path_in_alu[12]), .E (n_433), .Q (n_463));
  AO221ST_X2 g26767(.A (n_417), .B (gm_Q_tmp[14]), .C (n_66), .D
       (CPU_Data_Path_in_alu[14]), .E (n_433), .Q (n_462));
  ON221ST_X1 g26768(.A (n_416), .B (n_81), .C (n_88), .D (n_21), .E
       (n_442), .Q (n_461));
  ON21ST_X1 g26769(.A (n_395), .B (n_291), .C (n_449), .Q (n_467));
  AN221ST_X1 g26770(.A (n_407), .B (n_56), .C (n_285), .D (n_361), .E
       (n_295), .Q (n_460));
  NO3ST_X1 g26771(.A (1'b0), .B (n_450), .C (CPU_SEL_BRANCH), .Q
       (n_466));
  AO222ST_X2 g26772(.A (n_390), .B (n_208), .C (n_415), .D
       (CPU_OPERAND[1]), .E (n_64), .F (CPU_Data_Path_in_alu[1]), .Q
       (n_459));
  AO222ST_X2 g26773(.A (n_29), .B (gm_Q_tmp[8]), .C (n_415), .D
       (CPU_OPERAND[8]), .E (n_64), .F (CPU_Data_Path_in_alu[8]), .Q
       (n_458));
  AO222ST_X2 g26774(.A (n_417), .B (gm_Q_tmp[9]), .C (n_415), .D
       (CPU_OPERAND[9]), .E (n_64), .F (CPU_Data_Path_in_alu[9]), .Q
       (n_457));
  MU2ST_X2 g26775(.IN0 (n_426), .IN1 (CPU_INDR[1]), .S (n_371), .Q
       (n_456));
  HAST_X2 g26776(.A (BOOTLOADER_INTERFACE_tmp[3]), .B (n_392), .CO
       (n_455), .S (n_454));
  FAST_X2 g26777(.A (CPU_OPERAND[2]), .B (CPU_INDR[2]), .CI (n_397),
       .CO (n_452), .S (n_453));
  INST_X3 g26778(.A (n_450), .Q (n_449));
  OR2ST_X1 g26781(.A (n_353), .B (n_427), .Q (n_451));
  AND2ST_X2 g26782(.A (n_429), .B (n_228), .Q (n_446));
  AN21ST_X1 g26784(.A (n_1168), .B (n_140), .C (n_292), .Q (n_450));
  ON21ST_X1 g26785(.A (n_408), .B (n_169), .C (n_147), .Q (n_448));
  ON21ST_X1 g26786(.A (CPU_Data_Path_in_alu[3]), .B (n_83), .C (n_430),
       .Q (n_447));
  MU2ST_X2 g26787(.IN0 (n_413), .IN1 (CPU_PC[6]), .S (CPU_PC[7]), .Q
       (n_444));
  AN22ST_X1 g26788(.A (n_417), .B (gm_Q_tmp[0]), .C (n_414), .D
       (PORT_IN[0]), .Q (n_443));
  AN22ST_X1 g26789(.A (n_417), .B (gm_Q_tmp[2]), .C (n_414), .D
       (PORT_IN[2]), .Q (n_442));
  AN22ST_X1 g26790(.A (n_29), .B (gm_Q_tmp[3]), .C (n_414), .D
       (PORT_IN[3]), .Q (n_441));
  AN22ST_X1 g26791(.A (n_29), .B (gm_Q_tmp[4]), .C (n_414), .D
       (PORT_IN[4]), .Q (n_440));
  AN22ST_X1 g26792(.A (n_29), .B (gm_Q_tmp[5]), .C (n_414), .D
       (PORT_IN[5]), .Q (n_439));
  AN22ST_X1 g26793(.A (n_29), .B (gm_Q_tmp[6]), .C (n_414), .D
       (PORT_IN[6]), .Q (n_438));
  AN22ST_X1 g26794(.A (n_417), .B (gm_Q_tmp[7]), .C (n_414), .D
       (PORT_IN[7]), .Q (n_437));
  MU2ST_X2 g26795(.IN0 (n_400), .IN1 (CPU_INDR[0]), .S (n_371), .Q
       (n_436));
  OA22ST_X2 g26796(.A (n_407), .B (n_25), .C (n_55), .D (n_361), .Q
       (n_435));
  EN2ST_X1 g26797(.A (n_255), .B (n_408), .Q (n_434));
  AND2ST_X2 g26799(.A (n_415), .B (CPU_OPERAND[10]), .Q (n_433));
  NO2I1ST_X1 g26800(.AN (n_419), .B (n_321), .Q (n_432));
  NA6I5ST_X1 g26801(.AN (CPU_Data_Path_in_alu[6]), .BN
       (CPU_Data_Path_in_alu[9]), .CN (CPU_Data_Path_in_alu[5]), .DN
       (CPU_Data_Path_in_alu[10]), .EN (CPU_Data_Path_in_alu[13]), .F
       (n_273), .Q (n_431));
  ON21ST_X1 g26802(.A (n_68), .B (n_1112), .C (n_407), .Q (n_430));
  ON221ST_X1 g26803(.A (n_296), .B (n_360), .C (n_284), .D (n_55), .E
       (n_294), .Q (n_429));
  NA3ST_X1 g26805(.A (n_389), .B (n_277), .C (n_322), .Q (n_427));
  AO22ST_X2 g26806(.A (n_8), .B (n_398), .C (n_283), .D (n_208), .Q
       (n_426));
  AO32ST_X2 g26807(.A (n_356), .B (n_22), .C (RST), .D
       (CPU_APB_GEN_MEM_en_w), .E (n_61), .Q (n_425));
  AN22ST_X1 g26808(.A (n_388), .B (CPU_Data_Path_in_alu[3]), .C
       (n_344), .D (n_171), .Q (n_424));
  ON22ST_X1 g26809(.A (n_387), .B (n_95), .C (n_294), .D (n_211), .Q
       (n_423));
  AN22ST_X1 g26810(.A (n_391), .B (CPU_ACC[11]), .C (n_11), .D (n_232),
       .Q (n_422));
  AO22ST_X2 g26811(.A (n_388), .B (CPU_Data_Path_in_alu[2]), .C
       (n_344), .D (n_165), .Q (n_421));
  MU2ST_X2 g26812(.IN0 (n_393), .IN1 (BOOTLOADER_INTERFACE_tmp[2]), .S
       (n_42), .Q (n_420));
  HAST_X2 g26813(.A (n_278), .B (n_340), .CO (n_419), .S (n_418));
  INST_X4 g26814(.A (n_416), .Q (n_415));
  AND2ST_X2 g26817(.A (n_60), .B (n_390), .Q (n_417));
  NA2ST_X1 g26818(.A (n_395), .B (CPU_PC[6]), .Q (n_413));
  NA2I1ST_X1 g26819(.AN (n_390), .B (n_22), .Q (n_416));
  AND2ST_X2 g26820(.A (CPU_GM_ADDR[8]), .B (n_390), .Q (n_414));
  ON21ST_X1 g26821(.A (n_26), .B (n_46), .C (n_386), .Q (n_412));
  ON21ST_X1 g26822(.A (n_157), .B (n_75), .C (n_386), .Q (n_411));
  ON21ST_X1 g26823(.A (n_157), .B (n_93), .C (n_386), .Q (n_410));
  ON21ST_X1 g26824(.A (n_26), .B (n_85), .C (n_386), .Q (n_409));
  ON21ST_X1 g26825(.A (n_157), .B (n_45), .C (n_386), .Q (n_404));
  ON21ST_X1 g26826(.A (n_26), .B (n_71), .C (n_386), .Q (n_403));
  OA21ST_X2 g26828(.A (n_361), .B (n_170), .C (n_159), .Q (n_408));
  AO32ST_X2 g26829(.A (n_329), .B (n_67), .C (n_290), .D
       (CPU_state[2]), .E (n_62), .Q (n_401));
  ON22ST_X1 g26830(.A (n_360), .B (n_111), .C
       (CPU_Data_Path_in_alu[2]), .D (n_80), .Q (n_407));
  AO222ST_X2 g26831(.A (n_348), .B (gm_Q_tmp[0]), .C (n_346), .D
       (PORT_IN[0]), .E (CPU_Data_Path_n_7530), .F (n_300), .Q (n_400));
  AN22ST_X1 g26832(.A (n_56), .B (n_360), .C (n_24), .D (n_284), .Q
       (n_399));
  MU2ST_X2 g26833(.IN0 (n_355), .IN1 (n_333), .S (n_20), .Q (n_406));
  MU2ST_X2 g26834(.IN0 (n_354), .IN1 (n_331), .S (n_88), .Q (n_405));
  FAST_X2 g26835(.A (CPU_OPERAND[1]), .B (CPU_INDR[1]), .CI (n_299),
       .CO (n_397), .S (n_398));
  INST_X4 g26836(.A (n_395), .Q (n_396));
  HAST_X2 g26837(.A (CPU_PC[5]), .B (n_121), .CO (n_395), .S (n_394));
  HAST_X2 g26838(.A (BOOTLOADER_INTERFACE_tmp[2]), .B (n_297), .CO
       (n_392), .S (n_393));
  INST_X4 g26840(.A (n_388), .Q (n_387));
  INST_X4 g26841(.A (n_388), .Q (n_386));
  NA2I1ST_X1 g26844(.AN (n_292), .B (n_350), .Q (n_384));
  OR2ST_X1 g26845(.A (n_370), .B (n_344), .Q (n_391));
  AND2ST_X2 g26846(.A (n_21), .B (n_362), .Q (n_390));
  NO2I1ST_X1 g26847(.AN (n_321), .B (n_372), .Q (n_389));
  AO31ST_X2 g26848(.A (CPU_en_ACC), .B (n_293), .C (n_974), .D (n_0),
       .Q (n_388));
  AO321ST_X2 g26849(.A (n_209), .B (n_76), .C (CPU_state[0]), .D
       (CPU_state[1]), .E (n_62), .F (n_292), .Q (n_383));
  AN21ST_X1 g26850(.A (n_53), .B (n_153), .C (n_351), .Q (n_382));
  ON22ST_X1 g26851(.A (n_334), .B (CPU_ACC[2]), .C (n_157), .D (n_135),
       .Q (n_375));
  ON22ST_X1 g26852(.A (n_334), .B (CPU_ACC[3]), .C (n_26), .D (n_159),
       .Q (n_374));
  AN22ST_X1 g26853(.A (n_336), .B (n_20), .C (n_210), .D (n_127), .Q
       (n_381));
  AN22ST_X1 g26854(.A (n_339), .B (n_20), .C (n_127), .D (n_155), .Q
       (n_380));
  AN22ST_X1 g26856(.A (n_335), .B (n_88), .C (n_207), .D (n_127), .Q
       (n_379));
  MU2ST_X2 g26857(.IN0 (n_324), .IN1 (n_327), .S (n_88), .Q (n_378));
  MU2ST_X2 g26858(.IN0 (n_323), .IN1 (n_325), .S (n_20), .Q (n_377));
  MU2ST_X2 g26859(.IN0 (n_337), .IN1 (n_225), .S
       (CPU_Data_Path_in_alu[2]), .Q (n_376));
  NA2I1ST_X1 g26876(.AN (n_86), .B (n_57), .Q (n_369));
  NA2I1ST_X1 g26877(.AN (n_347), .B (n_279), .Q (n_372));
  NA2I1ST_X1 g26878(.AN (n_330), .B (n_22), .Q (n_371));
  NA3ST_X1 g26879(.A (n_281), .B (n_264), .C (CPU_en_ACC), .Q (n_370));
  INST_X4 g26880(.A (n_365), .Q (n_366));
  INST_X4 g26881(.A (n_363), .Q (n_364));
  NO2I1ST_X1 g26882(.AN (n_347), .B (n_340), .Q (n_368));
  NO4ST_X1 g26883(.A (n_216), .B (n_251), .C (n_222), .D (n_247), .Q
       (n_367));
  NO4ST_X1 g26884(.A (n_218), .B (n_245), .C (n_249), .D (n_243), .Q
       (n_365));
  NO4ST_X1 g26886(.A (n_217), .B (n_235), .C (n_243), .D (n_215), .Q
       (n_363));
  AN221ST_X1 g26887(.A (n_238), .B (n_974), .C (n_133), .D (n_1003), .E
       (n_282), .Q (n_362));
  AN21ST_X1 g26888(.A (n_130), .B (n_154), .C (n_320), .Q (n_351));
  AN21ST_X1 g26889(.A (n_284), .B (n_165), .C (n_134), .Q (n_361));
  AN221ST_X1 g26890(.A (n_219), .B (CPU_ACC[1]), .C (n_95), .D
       (CPU_ACC[0]), .E (n_173), .Q (n_360));
  NO4ST_X1 g26891(.A (n_248), .B (n_250), .C (n_214), .D (n_215), .Q
       (n_359));
  NO4ST_X1 g26892(.A (n_223), .B (n_240), .C (n_239), .D (n_226), .Q
       (n_358));
  NO4ST_X1 g26894(.A (n_223), .B (n_224), .C (n_233), .D (n_222), .Q
       (n_357));
  AO32ST_X2 g26895(.A (CPU_Control_Unit_n_848), .B (n_167), .C (n_109),
       .D (n_293), .E (n_78), .Q (n_356));
  AN221ST_X1 g26896(.A (n_209), .B (CPU_state[1]), .C (CPU_state[0]),
       .D (n_62), .E (n_267), .Q (n_350));
  AN222ST_X1 g26897(.A (n_210), .B (CPU_Data_Path_in_alu[1]), .C
       (n_50), .D (n_79), .E (n_174), .F (CPU_ACC[3]), .Q (n_355));
  AN222ST_X1 g26898(.A (n_50), .B (CPU_ACC[13]), .C (n_207), .D
       (CPU_Data_Path_in_alu[1]), .E (n_173), .F (n_43), .Q (n_354));
  MU2ST_X2 g26899(.IN0 (n_298), .IN1 (BOOTLOADER_INTERFACE_tmp[1]), .S
       (n_63), .Q (n_349));
  EN2ST_X1 g26900(.A (n_115), .B (n_272), .Q (n_353));
  EO2ST_X1 g26901(.A (n_201), .B (n_270), .Q (n_352));
  INST_X3 g26902(.A (n_343), .Q (n_342));
  INST_X4 g26905(.A (n_337), .Q (n_338));
  INST_X4 g26908(.A (n_331), .Q (n_332));
  AND2ST_X2 g26918(.A (n_60), .B (n_283), .Q (n_348));
  NA2ST_X1 g26919(.A (n_1173), .B (n_206), .Q (n_347));
  AND2ST_X2 g26920(.A (CPU_GM_ADDR[8]), .B (n_283), .Q (n_346));
  AND2ST_X2 g26922(.A (n_0), .B (n_1029), .Q (n_344));
  AND2ST_X2 g26923(.A (n_288), .B (CPU_OPCODE[0]), .Q (n_343));
  AND2ST_X2 g26924(.A (n_288), .B (n_78), .Q (n_341));
  NO2ST_X1 g26925(.A (n_206), .B (n_1173), .Q (n_340));
  AN31ST_X1 g26926(.A (n_974), .B (n_163), .C (n_1029), .D (n_8), .Q
       (n_330));
  ON221ST_X1 g26927(.A (n_51), .B (n_83), .C (n_100), .D (n_48), .E
       (n_269), .Q (n_339));
  AN221ST_X1 g26928(.A (n_136), .B (n_43), .C (n_14), .D (CPU_ACC[14]),
       .E (n_271), .Q (n_337));
  ON211ST_X1 g26929(.A (n_52), .B (n_83), .C (n_265), .D (n_212), .Q
       (n_336));
  ON221ST_X1 g26930(.A (n_51), .B (n_45), .C (n_106), .D (n_48), .E
       (n_268), .Q (n_335));
  AN211ST_X1 g26931(.A (n_125), .B (n_167), .C (n_139), .D
       (CPU_Control_Unit_n_370), .Q (n_329));
  NA3ST_X1 g26932(.A (n_974), .B (n_254), .C (CPU_en_ACC), .Q (n_334));
  AN221ST_X1 g26933(.A (n_27), .B (n_1042), .C (n_13), .D (CPU_ACC[4]),
       .E (n_287), .Q (n_333));
  AN221ST_X1 g26934(.A (n_27), .B (n_90), .C (n_14), .D (n_89), .E
       (n_274), .Q (n_331));
  INST_X4 g26935(.A (n_327), .Q (n_328));
  INST_X4 g26936(.A (n_325), .Q (n_326));
  AN221ST_X1 g26937(.A (n_141), .B (n_98), .C (n_13), .D (CPU_ACC[3]),
       .E (n_275), .Q (n_327));
  AN221ST_X1 g26938(.A (n_27), .B (n_89), .C (n_14), .D (n_43), .E
       (n_286), .Q (n_325));
  AN222ST_X1 g26939(.A (n_136), .B (CPU_ACC[1]), .C (n_155), .D
       (CPU_Data_Path_in_alu[1]), .E (n_15), .F (n_79), .Q (n_324));
  AN222ST_X1 g26940(.A (n_174), .B (CPU_ACC[13]), .C (n_136), .D
       (CPU_ACC[14]), .E (n_141), .F (CPU_ACC[15]), .Q (n_323));
  AN22ST_X1 g26941(.A (n_237), .B (n_990), .C (n_151), .D (n_162), .Q
       (n_320));
  MU2ST_X2 g26942(.IN0 (CPU_OPERAND[3]), .IN1 (pm_Q[3]), .S (n_34), .Q
       (n_319));
  MU2ST_X2 g26943(.IN0 (CPU_OPERAND[1]), .IN1 (pm_Q[1]), .S (n_33), .Q
       (n_318));
  MU2ST_X2 g26944(.IN0 (n_1003), .IN1 (pm_Q[12]), .S (n_33), .Q
       (n_317));
  MU2ST_X2 g26945(.IN0 (n_990), .IN1 (pm_Q[13]), .S (n_5), .Q (n_316));
  MU2ST_X2 g26946(.IN0 (CPU_OPCODE[3]), .IN1 (pm_Q[14]), .S (n_34), .Q
       (n_315));
  MU2ST_X2 g26947(.IN0 (CPU_OPCODE[4]), .IN1 (pm_Q[15]), .S (n_34), .Q
       (n_314));
  MU2ST_X2 g26948(.IN0 (CPU_OPERAND[5]), .IN1 (pm_Q[5]), .S (n_33), .Q
       (n_313));
  MU2ST_X2 g26949(.IN0 (CPU_OPERAND[2]), .IN1 (pm_Q[2]), .S (n_33), .Q
       (n_312));
  MU2ST_X2 g26950(.IN0 (CPU_OPERAND[6]), .IN1 (pm_Q[6]), .S (n_33), .Q
       (n_311));
  MU2ST_X2 g26951(.IN0 (CPU_OPERAND[7]), .IN1 (pm_Q[7]), .S (n_34), .Q
       (n_310));
  MU2ST_X2 g26952(.IN0 (CPU_OPERAND[4]), .IN1 (pm_Q[4]), .S (n_33), .Q
       (n_309));
  MU2ST_X2 g26953(.IN0 (CPU_OPERAND[9]), .IN1 (pm_Q[9]), .S (n_34), .Q
       (n_308));
  MU2ST_X2 g26954(.IN0 (CPU_OPCODE[0]), .IN1 (pm_Q[11]), .S (n_33), .Q
       (n_307));
  MU2ST_X2 g26955(.IN0 (CPU_OPERAND[8]), .IN1 (pm_Q[8]), .S (n_33), .Q
       (n_306));
  MU2ST_X2 g26956(.IN0 (CPU_OPERAND[10]), .IN1 (pm_Q[10]), .S (n_34),
       .Q (n_305));
  MU2ST_X2 g26957(.IN0 (CPU_OPERAND[0]), .IN1 (pm_Q[0]), .S (n_34), .Q
       (n_304));
  EN2ST_X1 g26958(.A (n_202), .B (n_220), .Q (n_322));
  EO2ST_X1 g26959(.A (n_153), .B (n_211), .Q (n_303));
  EN2ST_X1 g26960(.A (n_130), .B (n_211), .Q (n_302));
  EN2ST_X1 g26961(.A (n_200), .B (n_112), .Q (n_321));
  EO2ST_X1 g26962(.A (n_206), .B (PC_UF), .Q (n_301));
  HAST_X2 g26963(.A (CPU_OPERAND[0]), .B (CPU_INDR[0]), .CO (n_299), .S
       (n_300));
  HAST_X2 g26964(.A (BOOTLOADER_INTERFACE_tmp[0]), .B
       (BOOTLOADER_INTERFACE_tmp[1]), .CO (n_297), .S (n_298));
  INST_X4 g26967(.A (n_295), .Q (n_294));
  INST_X4 g26968(.A (n_292), .Q (n_291));
  INST_X4 g26969(.A (n_289), .Q (n_290));
  NA2I1ST_X1 g26988(.AN (n_235), .B (n_236), .Q (n_287));
  NA2ST_X1 g26989(.A (n_213), .B (n_162), .Q (n_296));
  AND2ST_X2 g26990(.A (n_237), .B (n_133), .Q (n_295));
  OR2ST_X1 g26991(.A (n_250), .B (n_245), .Q (n_286));
  NO2I1ST_X1 g26992(.AN (CPU_OPCODE[4]), .B (n_238), .Q (n_293));
  AND2ST_X2 g26993(.A (n_5), .B (HOLDn), .Q (n_292));
  AND2ST_X2 g26994(.A (n_254), .B (n_78), .Q (n_289));
  AND2ST_X2 g26996(.A (n_213), .B (n_133), .Q (n_288));
  INST_X4 g26998(.A (n_281), .Q (n_282));
  INST_X4 g26999(.A (n_278), .Q (n_279));
  INST_X4 g27000(.A (n_277), .Q (n_276));
  NA2I1ST_X1 g27001(.AN (n_224), .B (n_221), .Q (n_275));
  OR2ST_X1 g27002(.A (n_251), .B (n_240), .Q (n_274));
  AND2ST_X2 g27003(.A (n_237), .B (n_162), .Q (n_285));
  NO4ST_X1 g27004(.A (CPU_Data_Path_in_alu[15]), .B
       (CPU_Data_Path_in_alu[4]), .C (CPU_Data_Path_in_alu[8]), .D
       (CPU_Data_Path_in_alu[7]), .Q (n_273));
  ON21ST_X1 g27005(.A (n_132), .B (CPU_Data_Path_add_105_28_n_53), .C
       (CPU_Data_Path_add_105_28_n_9140), .Q (n_272));
  AO21ST_X2 g27006(.A (n_141), .B (CPU_ACC[13]), .C (n_214), .Q
       (n_271));
  ON211ST_X1 g27007(.A (CPU_Data_Path_add_105_28_n_9140), .B
       (CPU_Data_Path_add_105_28_n_63), .C
       (CPU_Data_Path_add_105_28_n_109), .D (n_873), .Q (n_270));
  AN21ST_X1 g27008(.A (n_141), .B (CPU_ACC[2]), .C (n_233), .Q (n_269));
  AN21ST_X1 g27009(.A (n_27), .B (n_43), .C (n_239), .Q (n_268));
  NA2ST_X1 g27010(.A (n_203), .B (n_128), .Q (n_284));
  NO4ST_X1 g27011(.A (n_62), .B (CPU_state[1]), .C (CPU_state[0]), .D
       (n_22), .Q (n_267));
  AND3ST_X4 g27012(.A (n_133), .B (n_974), .C (n_163), .Q (n_283));
  MU2ST_X2 g27013(.IN0 (n_119), .IN1 (CPU_APB_GEN_MEM_state[1]), .S
       (n_62), .Q (n_266));
  AN22ST_X1 g27014(.A (n_167), .B (n_96), .C (n_78), .D (n_1016), .Q
       (n_281));
  AN22ST_X1 g27015(.A (n_50), .B (CPU_ACC[4]), .C (n_13), .D
       (CPU_ACC[2]), .Q (n_265));
  AN22ST_X1 g27016(.A (n_125), .B (n_161), .C (n_163), .D
       (CPU_OPCODE[2]), .Q (n_264));
  MU2ST_X2 g27017(.IN0 (CPU_ACC[0]), .IN1 (PORT_OUT[0]), .S (n_1169),
       .Q (n_263));
  MU2ST_X2 g27018(.IN0 (n_1164), .IN1 (PORT_OUT[1]), .S (n_1169), .Q
       (n_262));
  MU2ST_X2 g27019(.IN0 (CPU_ACC[7]), .IN1 (PORT_OUT[7]), .S (n_1169),
       .Q (n_261));
  MU2ST_X2 g27020(.IN0 (n_1055), .IN1 (PORT_OUT[6]), .S (n_1169), .Q
       (n_260));
  MU2ST_X2 g27021(.IN0 (n_98), .IN1 (PORT_OUT[4]), .S (n_1169), .Q
       (n_259));
  MU2ST_X2 g27022(.IN0 (n_1042), .IN1 (PORT_OUT[5]), .S (n_1169), .Q
       (n_258));
  MU2ST_X2 g27023(.IN0 (CPU_ACC[3]), .IN1 (PORT_OUT[3]), .S (n_1169),
       .Q (n_257));
  MU2ST_X2 g27024(.IN0 (n_79), .IN1 (PORT_OUT[2]), .S (n_1169), .Q
       (n_256));
  EN2ST_X1 g27026(.A (n_1171), .B (CPU_Data_Path_add_105_28_n_76), .Q
       (n_278));
  EN2ST_X1 g27027(.A (n_143), .B (n_1176), .Q (n_277));
  INST_X4 g27028(.A (n_252), .Q (n_253));
  NA2ST_X1 g27033(.A (n_132), .B (CPU_Data_Path_add_105_28_n_9139), .Q
       (n_220));
  NO2I1ST_X1 g27034(.AN (n_147), .B (n_169), .Q (n_255));
  AND2ST_X2 g27035(.A (n_125), .B (n_162), .Q (n_254));
  NO2I1ST_X1 g27036(.AN (n_124), .B (n_148), .Q (n_252));
  AND2ST_X2 g27037(.A (n_173), .B (n_86), .Q (n_251));
  AND2ST_X2 g27038(.A (n_136), .B (CPU_ACC[10]), .Q (n_250));
  AND2ST_X2 g27039(.A (n_141), .B (n_17), .Q (n_249));
  AND2ST_X2 g27040(.A (n_14), .B (n_86), .Q (n_248));
  NA2ST_X1 g27041(.A (n_49), .B (n_97), .Q (n_219));
  AND2ST_X2 g27042(.A (n_50), .B (n_17), .Q (n_247));
  NA2I1ST_X1 g27043(.AN (n_142), .B (n_158), .Q (n_246));
  AND2ST_X2 g27044(.A (n_174), .B (CPU_ACC[9]), .Q (n_245));
  NO2I1ST_X1 g27045(.AN (n_150), .B (n_176), .Q (n_244));
  AND2ST_X2 g27046(.A (n_136), .B (CPU_ACC[8]), .Q (n_243));
  AND2ST_X2 g27047(.A (n_13), .B (CPU_ACC[6]), .Q (n_218));
  NO2I1ST_X1 g27048(.AN (n_166), .B (n_156), .Q (n_242));
  NO2I1ST_X1 g27049(.AN (n_129), .B (n_160), .Q (n_241));
  AND2ST_X2 g27050(.A (n_50), .B (CPU_ACC[9]), .Q (n_240));
  AND2ST_X2 g27051(.A (n_15), .B (CPU_ACC[10]), .Q (n_239));
  AND2ST_X2 g27052(.A (n_14), .B (CPU_ACC[10]), .Q (n_217));
  NA2I1ST_X1 g27053(.AN (CPU_OPCODE[2]), .B (n_163), .Q (n_238));
  AND2ST_X2 g27054(.A (n_151), .B (n_96), .Q (n_237));
  NA2I1ST_X1 g27055(.AN (n_105), .B (n_50), .Q (n_236));
  AND2ST_X2 g27056(.A (n_174), .B (CPU_ACC[7]), .Q (n_235));
  NO2I1ST_X1 g27057(.AN (n_177), .B (n_122), .Q (n_234));
  AND2ST_X2 g27058(.A (n_15), .B (n_98), .Q (n_233));
  NA2I1ST_X1 g27059(.AN (n_149), .B (n_123), .Q (n_232));
  AND2ST_X2 g27060(.A (n_171), .B (n_159), .Q (n_231));
  NA2I1ST_X1 g27061(.AN (n_137), .B (n_168), .Q (n_230));
  NO2I1ST_X1 g27062(.AN (n_172), .B (n_131), .Q (n_229));
  AND2ST_X2 g27063(.A (n_165), .B (n_135), .Q (n_228));
  NA2I1ST_X1 g27064(.AN (n_126), .B (n_152), .Q (n_227));
  AND2ST_X2 g27065(.A (n_141), .B (CPU_ACC[8]), .Q (n_226));
  NA2I1ST_X1 g27066(.AN (n_93), .B (n_15), .Q (n_225));
  AND2ST_X2 g27067(.A (n_50), .B (CPU_ACC[5]), .Q (n_224));
  AND2ST_X2 g27068(.A (n_49), .B (CPU_ACC[7]), .Q (n_223));
  AND2ST_X2 g27069(.A (n_27), .B (CPU_ACC[6]), .Q (n_222));
  NA2I1ST_X1 g27070(.AN (n_105), .B (n_15), .Q (n_221));
  AND2ST_X2 g27071(.A (n_13), .B (CPU_ACC[5]), .Q (n_216));
  AND2ST_X2 g27073(.A (n_27), .B (n_1151), .Q (n_215));
  NA2I1ST_X1 g27074(.AN (n_85), .B (n_49), .Q (n_204));
  AND2ST_X2 g27075(.A (n_173), .B (CPU_ACC[11]), .Q (n_214));
  AND2ST_X2 g27076(.A (n_151), .B (CPU_OPCODE[1]), .Q (n_213));
  NA2ST_X1 g27077(.A (n_175), .B (n_153), .Q (n_203));
  NA2I1ST_X1 g27078(.AN (n_84), .B (n_174), .Q (n_212));
  NA2ST_X1 g27079(.A (n_128), .B (n_175), .Q (n_211));
  AO21ST_X2 g27081(.A (n_107), .B (CPU_ACC[1]), .C (n_153), .Q (n_210));
  AN21ST_X1 g27082(.A (CPU_OPERAND[5]), .B (CPU_PC[5]), .C
       (CPU_Data_Path_add_105_28_n_53), .Q (n_202));
  AN21ST_X1 g27083(.A (CPU_PC[7]), .B (CPU_OPERAND[7]), .C
       (CPU_Data_Path_add_105_28_n_59), .Q (n_201));
  AN21ST_X1 g27084(.A (CPU_OPERAND[3]), .B (CPU_PC[3]), .C
       (CPU_Data_Path_add_105_28_n_47), .Q (n_200));
  NO3ST_X1 g27085(.A (n_62), .B (CPU_state[2]), .C (n_21), .Q (n_209));
  MU2ST_X2 g27086(.IN0 (MISO), .IN1 (BOOTLOADER_wdata[15]), .S (PROG),
       .Q (n_199));
  MU2ST_X2 g27087(.IN0 (BOOTLOADER_wdata[9]), .IN1
       (BOOTLOADER_wdata[10]), .S (n_36), .Q (n_198));
  MU2ST_X2 g27088(.IN0 (BOOTLOADER_wdata[10]), .IN1
       (BOOTLOADER_wdata[11]), .S (n_37), .Q (n_197));
  MU2ST_X2 g27089(.IN0 (BOOTLOADER_wdata[1]), .IN1
       (BOOTLOADER_wdata[2]), .S (n_38), .Q (n_196));
  MU2ST_X2 g27090(.IN0 (BOOTLOADER_wdata[11]), .IN1
       (BOOTLOADER_wdata[12]), .S (n_39), .Q (n_195));
  MU2ST_X2 g27091(.IN0 (BOOTLOADER_wdata[14]), .IN1
       (BOOTLOADER_wdata[15]), .S (n_40), .Q (n_194));
  MU2ST_X2 g27092(.IN0 (BOOTLOADER_wdata[5]), .IN1
       (BOOTLOADER_wdata[6]), .S (n_41), .Q (n_193));
  MU2ST_X2 g27093(.IN0 (BOOTLOADER_wdata[0]), .IN1
       (BOOTLOADER_wdata[1]), .S (n_42), .Q (n_192));
  MU2ST_X2 g27094(.IN0 (BOOTLOADER_wdata[2]), .IN1
       (BOOTLOADER_wdata[3]), .S (n_36), .Q (n_191));
  MU2ST_X2 g27095(.IN0 (BOOTLOADER_wdata[6]), .IN1
       (BOOTLOADER_wdata[7]), .S (n_37), .Q (n_190));
  MU2ST_X2 g27096(.IN0 (BOOTLOADER_wdata[3]), .IN1
       (BOOTLOADER_wdata[4]), .S (n_38), .Q (n_189));
  MU2ST_X2 g27097(.IN0 (BOOTLOADER_wdata[8]), .IN1
       (BOOTLOADER_wdata[7]), .S (PROG), .Q (n_188));
  MU2ST_X2 g27098(.IN0 (BOOTLOADER_wdata[8]), .IN1
       (BOOTLOADER_wdata[9]), .S (n_39), .Q (n_187));
  MU2ST_X2 g27099(.IN0 (gm_Q_tmp[1]), .IN1 (PORT_IN[1]), .S
       (CPU_GM_ADDR[8]), .Q (n_208));
  MU2ST_X2 g27100(.IN0 (MOSI), .IN1 (BOOTLOADER_wdata[0]), .S (n_40),
       .Q (n_186));
  MU2ST_X2 g27101(.IN0 (BOOTLOADER_wdata[13]), .IN1
       (BOOTLOADER_wdata[14]), .S (n_41), .Q (n_185));
  MU2ST_X2 g27102(.IN0 (CPU_ACC[14]), .IN1 (CPU_ACC[15]), .S
       (CPU_Data_Path_in_alu[0]), .Q (n_207));
  MU2ST_X2 g27103(.IN0 (BOOTLOADER_wdata[12]), .IN1
       (BOOTLOADER_wdata[13]), .S (n_42), .Q (n_184));
  MU2ST_X2 g27104(.IN0 (BOOTLOADER_wdata[4]), .IN1
       (BOOTLOADER_wdata[5]), .S (n_37), .Q (n_183));
  EO2ST_X1 g27105(.A (CPU_PC[4]), .B (CPU_Data_Path_add_103_26_n_72),
       .Q (n_182));
  EN2ST_X1 g27106(.A (CPU_PC[0]), .B (CPU_OPERAND[0]), .Q (n_206));
  EN2ST_X1 g27108(.A (n_63), .B (BOOTLOADER_INTERFACE_tmp[0]), .Q
       (n_180));
  EO2ST_X1 g27109(.A (CPU_PC[0]), .B (CPU_PC[1]), .Q (n_179));
  EN2ST_X1 g27110(.A (CPU_ACC[15]), .B (CPU_Data_Path_in_alu[15]), .Q
       (n_205));
  INST_X4 g27112(.A (n_54), .Q (n_174));
  INST_X4 g27113(.A (n_54), .Q (n_173));
  INST_X3 g27116(.A (n_170), .Q (n_171));
  INST_X4 g27117(.A (n_162), .Q (n_161));
  INST_X4 g27120(.A (n_155), .Q (n_154));
  NA2I1ST_X1 g27121(.AN (n_1042), .B (n_77), .Q (n_177));
  NO2ST_X1 g27122(.A (n_17), .B (CPU_Data_Path_in_alu[7]), .Q (n_176));
  NA2ST_X1 g27123(.A (n_95), .B (n_100), .Q (n_175));
  NA2ST_X1 g27124(.A (n_95), .B (n_107), .Q (n_54));
  NA2I1ST_X1 g27125(.AN (n_1055), .B (n_69), .Q (n_172));
  NO2I1ST_X1 g27126(.AN (n_75), .B (CPU_Data_Path_in_alu[14]), .Q
       (n_146));
  AND2ST_X2 g27127(.A (n_68), .B (n_83), .Q (n_170));
  AND2ST_X2 g27128(.A (n_104), .B (n_99), .Q (n_169));
  NA2I1ST_X1 g27129(.AN (n_86), .B (n_73), .Q (n_168));
  NO2ST_X1 g27131(.A (n_1029), .B (n_990), .Q (n_167));
  NA2I1ST_X1 g27132(.AN (n_1125), .B (n_87), .Q (n_166));
  NA2I1ST_X1 g27133(.AN (n_79), .B (n_88), .Q (n_165));
  AND2ST_X2 g27134(.A (n_20), .B (n_95), .Q (n_164));
  AND2ST_X2 g27135(.A (n_96), .B (n_1016), .Q (n_163));
  NO2I1ST_X1 g27136(.AN (n_990), .B (CPU_OPCODE[4]), .Q (n_162));
  AND2ST_X2 g27137(.A (CPU_Data_Path_in_alu[8]), .B (n_44), .Q (n_144));
  NO2I1ST_X1 g27138(.AN (n_1086), .B (CPU_Data_Path_in_alu[14]), .Q
       (n_160));
  NA2I1ST_X1 g27139(.AN (n_83), .B (CPU_Data_Path_in_alu[3]), .Q
       (n_159));
  NO2I1ST_X1 g27140(.AN (CPU_Data_Path_add_105_28_n_9139), .B
       (CPU_Data_Path_add_105_28_n_57), .Q (n_143));
  NA2I1ST_X1 g27141(.AN (CPU_ACC[12]), .B (CPU_Data_Path_in_alu[12]),
       .Q (n_158));
  NA2ST_X1 g27142(.A (n_928), .B (n_109), .Q (n_157));
  AND2ST_X2 g27143(.A (CPU_Data_Path_in_alu[13]), .B (CPU_ACC[13]), .Q
       (n_156));
  AND2ST_X2 g27144(.A (n_107), .B (CPU_ACC[0]), .Q (n_155));
  AND2ST_X2 g27145(.A (n_12), .B (CPU_ACC[0]), .Q (n_153));
  NA2I1ST_X1 g27146(.AN (n_85), .B (n_108), .Q (n_152));
  AND2ST_X2 g27147(.A (CPU_en_ACC), .B (n_109), .Q (n_151));
  NA2ST_X1 g27148(.A (CPU_Data_Path_in_alu[7]), .B (CPU_ACC[7]), .Q
       (n_150));
  AND2ST_X2 g27149(.A (CPU_Data_Path_in_alu[11]), .B (n_45), .Q
       (n_149));
  NO2I1ST_X1 g27150(.AN (n_1138), .B (CPU_Data_Path_in_alu[10]), .Q
       (n_148));
  NA2I1ST_X1 g27151(.AN (n_99), .B (CPU_Data_Path_in_alu[4]), .Q
       (n_147));
  INST_X2 g27153(.A (n_140), .Q (n_139));
  INST_X4 g27154(.A (n_51), .Q (n_136));
  INST_X3 g27157(.A (n_134), .Q (n_135));
  NO2I1ST_X1 g27161(.AN (CPU_ACC[12]), .B (CPU_Data_Path_in_alu[12]),
       .Q (n_142));
  NO2I1ST_X1 g27162(.AN (CPU_PC[4]), .B
       (CPU_Data_Path_add_103_26_n_72), .Q (n_121));
  AND2ST_X2 g27163(.A (n_107), .B (CPU_Data_Path_in_alu[1]), .Q
       (n_141));
  NA2I1ST_X1 g27164(.AN (n_98), .B (CPU_Data_Path_in_alu[4]), .Q
       (n_120));
  AND2ST_X2 g27165(.A (n_65), .B (HOLDn), .Q (n_140));
  NO2I1ST_X1 g27166(.AN (CPU_APB_GEN_MEM_state[0]), .B
       (CPU_APB_GEN_MEM_state[1]), .Q (n_119));
  AND2ST_X2 g27168(.A (CPU_Data_Path_in_alu[8]), .B (n_86), .Q (n_137));
  NA2ST_X1 g27170(.A (n_95), .B (CPU_Data_Path_in_alu[0]), .Q (n_51));
  AND2ST_X2 g27171(.A (CPU_Data_Path_in_alu[2]), .B (n_79), .Q (n_134));
  NA2I1ST_X1 g27172(.AN (n_17), .B (CPU_Data_Path_in_alu[7]), .Q
       (n_117));
  AND2ST_X2 g27173(.A (n_990), .B (CPU_OPCODE[4]), .Q (n_133));
  NA2I1ST_X1 g27174(.AN (CPU_Data_Path_add_105_28_n_57), .B (n_1176),
       .Q (n_132));
  AND2ST_X2 g27175(.A (CPU_Data_Path_in_alu[6]), .B (n_105), .Q
       (n_116));
  AND2ST_X2 g27176(.A (CPU_Data_Path_in_alu[6]), .B (n_1055), .Q
       (n_131));
  NA2I1ST_X1 g27177(.AN (n_1099), .B (CPU_Data_Path_in_alu[0]), .Q
       (n_130));
  NA2I1ST_X1 g27178(.AN (CPU_ACC[14]), .B (CPU_Data_Path_in_alu[14]),
       .Q (n_129));
  NA2I1ST_X1 g27179(.AN (n_100), .B (n_10), .Q (n_128));
  AND2ST_X2 g27180(.A (n_9), .B (n_95), .Q (n_127));
  AND2ST_X2 g27181(.A (CPU_Data_Path_in_alu[9]), .B (n_85), .Q (n_126));
  NA2I1ST_X1 g27182(.AN (CPU_Data_Path_add_105_28_n_63), .B (n_873), .Q
       (n_115));
  AND2ST_X2 g27183(.A (CPU_OPCODE[3]), .B (n_1003), .Q (n_125));
  AND2ST_X2 g27184(.A (CPU_Data_Path_in_alu[0]), .B (n_10), .Q (n_49));
  AND2ST_X2 g27185(.A (CPU_Data_Path_in_alu[13]), .B (n_106), .Q
       (n_114));
  NA2I1ST_X1 g27187(.AN (n_941), .B (CPU_Data_Path_add_105_28_n_9136),
       .Q (n_112));
  NA2I1ST_X1 g27188(.AN (CPU_ACC[10]), .B (CPU_Data_Path_in_alu[10]),
       .Q (n_124));
  AND2ST_X2 g27189(.A (n_9), .B (n_80), .Q (n_111));
  NA2I1ST_X1 g27191(.AN (CPU_Data_Path_in_alu[11]), .B (CPU_ACC[11]),
       .Q (n_123));
  AND2ST_X2 g27192(.A (CPU_Data_Path_in_alu[5]), .B (n_1042), .Q
       (n_122));
  INST_X4 g27194(.A (CPU_Data_Path_in_alu[9]), .Q (n_108));
  INST_X4 g27195(.A (CPU_Data_Path_in_alu[0]), .Q (n_107));
  INST_X4 g27196(.A (CPU_ACC[13]), .Q (n_106));
  INST_X3 g27198(.A (CPU_Data_Path_in_alu[4]), .Q (n_104));
  INST_X4 g27199(.A (CPU_Data_Path_in_alu[14]), .Q (n_103));
  INST_X2 g27200(.A (CPU_OPERAND[7]), .Q (n_101));
  INST_X3 g27201(.A (CPU_ACC[1]), .Q (n_100));
  INST_X3 g27202(.A (CPU_ACC[4]), .Q (n_99));
  INST_X4 g27204(.A (n_99), .Q (n_98));
  INST_X3 g27207(.A (CPU_ACC[0]), .Q (n_97));
  INST_X4 g27209(.A (CPU_Data_Path_in_alu[1]), .Q (n_95));
  INST_X2 g27210(.A (CPU_OPERAND[4]), .Q (n_94));
  INST_X3 g27211(.A (CPU_ACC[15]), .Q (n_93));
  INST_X4 g27212(.A (CPU_Data_Path_in_alu[7]), .Q (n_92));
  INST_X2 g27213(.A (CPU_OPERAND[0]), .Q (n_91));
  INST_X4 g27215(.A (n_46), .Q (n_90));
  INST_X4 g27218(.A (CPU_ACC[10]), .Q (n_46));
  INST_X4 g27221(.A (n_45), .Q (n_89));
  INST_X4 g27223(.A (CPU_ACC[11]), .Q (n_45));
  INST_X4 g27225(.A (CPU_Data_Path_in_alu[2]), .Q (n_88));
  INST_X4 g27226(.A (CPU_Data_Path_in_alu[13]), .Q (n_87));
  INST_X4 g27229(.A (n_44), .Q (n_86));
  INST_X3 g27230(.A (CPU_ACC[8]), .Q (n_44));
  INST_X4 g27231(.A (CPU_ACC[9]), .Q (n_85));
  INST_X4 g27233(.A (CPU_ACC[3]), .Q (n_83));
  INST_X2 g27234(.A (CPU_OPERAND[5]), .Q (n_82));
  INST_X2 g27235(.A (CPU_OPERAND[2]), .Q (n_81));
  INST_X3 g27236(.A (CPU_ACC[2]), .Q (n_80));
  INST_X4 g27238(.A (n_80), .Q (n_79));
  INST_X4 g27242(.A (CPU_Data_Path_in_alu[5]), .Q (n_77));
  INST_X3 g27243(.A (CPU_state[1]), .Q (n_76));
  INST_X4 g27244(.A (CPU_ACC[14]), .Q (n_75));
  INST_X2 g27246(.A (CPU_PC[0]), .Q (n_74));
  INST_X4 g27247(.A (CPU_Data_Path_in_alu[8]), .Q (n_73));
  INST_X2 g27248(.A (CPU_OPERAND[3]), .Q (n_72));
  INST_X4 g27250(.A (n_71), .Q (n_43));
  INST_X4 g27251(.A (CPU_ACC[12]), .Q (n_71));
  INST_X2 g27255(.A (CPU_OPERAND[6]), .Q (n_70));
  INST_X4 g27256(.A (CPU_Data_Path_in_alu[6]), .Q (n_69));
  INST_X4 g27257(.A (CPU_Data_Path_in_alu[3]), .Q (n_68));
  INST_X4 g27258(.A (n_1179), .Q (n_67));
  INST_X4 g27262(.A (n_65), .Q (n_64));
  INST_X4 g27264(.A (PROG), .Q (n_63));
  INST_X4 g27265(.A (HOLDn), .Q (n_62));
  INST_X4 g27266(.A (RST), .Q (n_61));
  INST_X4 g27267(.A (CPU_GM_ADDR[8]), .Q (n_60));
  INST_X4 drc_bufs27268(.A (PROG), .Q (n_42));
  INST_X4 drc_bufs27269(.A (PROG), .Q (n_41));
  INST_X4 drc_bufs27270(.A (PROG), .Q (n_40));
  INST_X4 drc_bufs27271(.A (PROG), .Q (n_39));
  INST_X4 drc_bufs27272(.A (PROG), .Q (n_38));
  INST_X4 drc_bufs27273(.A (PROG), .Q (n_37));
  INST_X4 drc_bufs27274(.A (PROG), .Q (n_36));
  INST_X4 drc_bufs27281(.A (n_4), .Q (n_34));
  INST_X4 drc_bufs27282(.A (n_4), .Q (n_33));
  INST_X4 drc_bufs27288(.A (n_3), .Q (n_32));
  INST_X4 drc_bufs27289(.A (n_3), .Q (n_31));
  INST_X4 drc_bufs27296(.A (n_57), .Q (n_30));
  INST_X3 drc_bufs27297(.A (n_334), .Q (n_57));
  INST_X4 drc_bufs27301(.A (n_28), .Q (n_29));
  INST_X3 drc_bufs27303(.A (n_417), .Q (n_28));
  INST_X4 drc_bufs27308(.A (n_52), .Q (n_27));
  INST_X3 drc_bufs27309(.A (n_141), .Q (n_52));
  INST_X4 drc_bufs27314(.A (n_53), .Q (n_26));
  INST_X3 drc_bufs27315(.A (n_157), .Q (n_53));
  INST_X4 drc_bufs27320(.A (n_56), .Q (n_25));
  INST_X3 drc_bufs27321(.A (n_296), .Q (n_56));
  INST_X4 drc_bufs27326(.A (n_55), .Q (n_24));
  INST_X3 drc_bufs27327(.A (n_285), .Q (n_55));
  INST_X4 drc_bufs27332(.A (n_58), .Q (n_23));
  INST_X3 drc_bufs27333(.A (n_341), .Q (n_58));
  INST_X4 drc_bufs27337(.A (n_66), .Q (n_22));
  INST_X4 drc_bufs27338(.A (n_66), .Q (n_21));
  INST_X4 drc_bufs27344(.A (n_19), .Q (n_20));
  INST_X3 drc_bufs27345(.A (n_88), .Q (n_19));
  INST_X4 drc_bufs27349(.A (n_59), .Q (n_18));
  INST_X3 drc_bufs27350(.A (n_391), .Q (n_59));
  INST_X4 drc_bufs27354(.A (n_16), .Q (n_17));
  INST_X3 drc_bufs27355(.A (CPU_ACC[7]), .Q (n_16));
  INST_X3 drc_bufs27359(.A (n_54), .Q (n_15));
  INST_X3 drc_bufs27364(.A (n_51), .Q (n_50));
  INST_X3 drc_bufs27368(.A (n_48), .Q (n_14));
  INST_X3 drc_bufs27369(.A (n_48), .Q (n_13));
  INST_X3 drc_bufs27370(.A (n_49), .Q (n_48));
  BUST_X3 drc_bufs27377(.A (CPU_Data_Path_in_alu[0]), .Q (n_12));
  BUST_X3 drc_bufs27382(.A (n_295), .Q (n_11));
  BUST_X3 drc_bufs27387(.A (CPU_Data_Path_in_alu[1]), .Q (n_10));
  BUST_X3 drc_bufs27392(.A (CPU_Data_Path_in_alu[2]), .Q (n_9));
  BUST_X3 drc_bufs27397(.A (CPU_Data_Path_n_7530), .Q (n_8));
  BUST_X3 drc_bufs27402(.A (n_343), .Q (n_7));
  BUST_X3 drc_bufs27407(.A (n_388), .Q (n_6));
  BUST_X3 drc_bufs27412(.A (n_34), .Q (n_5));
  OR3ST_X1 g18997(.A (CPU_state[0]), .B (n_76), .C (CPU_state[2]), .Q
       (n_4));
  OR2ST_X1 g27413(.A (n_815), .B (n_63), .Q (n_3));
  NA4I2ST_X1 g27414(.AN (n_249), .BN (n_248), .C (n_236), .D (n_212),
       .Q (n_2));
  NA4I2ST_X1 g27415(.AN (n_226), .BN (n_247), .C (n_204), .D (n_221),
       .Q (n_1));
  NO2I1ST_X1 g27416(.AN (n_213), .B (CPU_OPCODE[2]), .Q (n_0));
  OR3ST_X1 g27418(.A (n_1003), .B (CPU_OPCODE[0]), .C (CPU_ZN[1]), .Q
       (n_960));
  FAST_X1 g27419(.A (CPU_Data_Path_in_alu[12]), .B (n_43), .CI (n_962),
       .CO (n_961), .S (UNCONNECTED));
  FAST_X1 g27420(.A (CPU_Data_Path_in_alu[11]), .B (n_89), .CI (n_963),
       .CO (n_962), .S (UNCONNECTED0));
  FAST_X1 g27421(.A (CPU_Data_Path_in_alu[10]), .B (n_90), .CI (n_645),
       .CO (n_963), .S (UNCONNECTED1));
  FAST_X1 g27422(.A (n_481), .B (CPU_Data_Path_in_alu[5]), .CI (n_84),
       .CO (n_964), .S (UNCONNECTED2));
  MU2ST_X1 g27423(.IN0 (n_1181), .IN1 (n_62), .S
       (CPU_APB_GEN_MEM_state[0]), .Q (n_966));
  AN211ST_X1 g27425(.A (n_1179), .B (CPU_ZN[1]), .C (n_289), .D
       (n_1175), .Q (n_967));
  INST_X4 drc_bufs27431(.A (n_78), .Q (n_974));
  INST_X3 drc_bufs27432(.A (CPU_OPCODE[0]), .Q (n_78));
  INST_X4 drc_bufs27446(.A (n_847), .Q (n_990));
  INST_X3 drc_bufs27447(.A (CPU_OPCODE[2]), .Q (n_847));
  INST_X4 drc_bufs27458(.A (n_96), .Q (n_1003));
  INST_X3 drc_bufs27459(.A (CPU_OPCODE[1]), .Q (n_96));
  INST_X3 drc_bufs27470(.A (n_109), .Q (n_1016));
  INST_X3 drc_bufs27471(.A (CPU_OPCODE[3]), .Q (n_109));
  INST_X3 drc_bufs27482(.A (n_846), .Q (n_1029));
  INST_X3 drc_bufs27483(.A (CPU_OPCODE[4]), .Q (n_846));
  INST_X3 drc_bufs27494(.A (n_84), .Q (n_1042));
  INST_X3 drc_bufs27495(.A (CPU_ACC[5]), .Q (n_84));
  INST_X3 drc_bufs27506(.A (n_105), .Q (n_1055));
  INST_X3 drc_bufs27507(.A (CPU_ACC[6]), .Q (n_105));
  BUST_X3 drc_bufs27523(.A (CPU_state[2]), .Q (n_1073));
  BUST_X3 drc_bufs27535(.A (CPU_ACC[14]), .Q (n_1086));
  BUST_X3 drc_bufs27547(.A (CPU_ACC[0]), .Q (n_1099));
  BUST_X3 drc_bufs27559(.A (CPU_ACC[3]), .Q (n_1112));
  BUST_X3 drc_bufs27571(.A (CPU_ACC[13]), .Q (n_1125));
  BUST_X3 drc_bufs27583(.A (CPU_ACC[10]), .Q (n_1138));
  BUST_X3 drc_bufs27595(.A (CPU_ACC[9]), .Q (n_1151));
  BUST_X3 drc_bufs27607(.A (CPU_ACC[1]), .Q (n_1164));
  AND2ST_X2 g27610(.A (CPU_Control_Unit_n_370), .B (CPU_ZN[0]), .Q
       (n_1167));
  NA5I2ST_X2 g27611(.AN (n_1167), .BN (CPU_Control_Unit_n_415), .C
       (n_967), .D (n_902), .E (n_913), .Q (n_1168));
  NA2I1ST_X1 g27612(.AN (n_843), .B (CPU_GM_ADDR[8]), .Q (n_1169));
  EO2ST_X1 g27613(.A (CPU_PC[3]), .B (n_895), .Q (n_1170));
  NA2ST_X1 g27614(.A (n_880), .B (CPU_Data_Path_add_105_28_n_9136), .Q
       (n_1171));
  NO2I1ST_X1 g27615(.AN (n_879), .B (n_951), .Q (n_1172));
  EN2ST_X1 g27616(.A (n_875), .B (n_1172), .Q (n_1173));
  EO2ST_X1 g27617(.A (CPU_PC[2]), .B (n_872), .Q (n_1174));
  AND3ST_X1 g27618(.A (CPU_Control_Unit_n_370), .B (CPU_OPCODE[0]), .C
       (CPU_ZN[1]), .Q (n_1175));
  OA21ST_X1 g27619(.A (n_1178), .B (n_941), .C (n_854), .Q (n_1176));
  NA6ST_X1 g27620(.A (CPU_PC[5]), .B (CPU_PC[4]), .C (CPU_PC[6]), .D
       (CPU_PC[7]), .E (CPU_en_ACC), .F (n_898), .Q (n_1177));
  AO21ST_X1 g27621(.A (CPU_PC[3]), .B (CPU_OPERAND[3]), .C (n_874), .Q
       (n_1178));
  NO3I1ST_X1 g27622(.AN (n_845), .B (CPU_OPCODE[1]), .C
       (CPU_OPCODE[0]), .Q (n_1179));
  AND3ST_X1 g27623(.A (n_449), .B (n_65), .C (n_289), .Q (n_1180));
  OA21ST_X1 g27624(.A (n_362), .B (n_356), .C (n_140), .Q (n_1181));
endmodule

